---

- job:
    name: cleanup-stalled-workers
    description: cleanup-stalled-workers
    project-type: pipeline
    properties:
      - build-discarder:
          num-to-keep: 120
    concurrent: false
    pipeline-scm:
      scm:
        - tf-jenkins
      script-path: pipelines/cleanup_stalled_workers.groovy
      lightweight-checkout: true
    triggers:
      - timed: '*/20 * * * *'
