---

- job:
    name: usage-report
    description: Generates report about too long locked VM-s
    project-type: pipeline
    properties:
      - build-discarder:
          num-to-keep: 60
    concurrent: false
    pipeline-scm:
      scm:
        - tf-jenkins
      script-path: pipelines/report.groovy
      lightweight-checkout: true
    triggers:
      - timed: '15 4 * * *'
