- job:
    name: 'update-jenkins-jobs'
    description: "Updates jenkins jobs"
    defaults: global
    properties:
      - build-discarder:
          num-to-keep: 30
    node: built-in
    wrappers:
        - workspace-cleanup:
            disable-deferred-wipeout: true
        - credentials-binding:
          - username-password-separated:
              credential-id: self-jenkins
              username: USER
              password: PASSWORD
          - username-password-separated:
              credential-id: gerrit.tungsten.io
              username: GERRIT_API_USER
              password: GERRIT_API_PASSWORD
    scm:
      - tf-jenkins
    builders:
      - shell: |
          #!/bin/bash -x
          if [[ -n $GERRIT_CHANGE_ID ]] ; then
            url=$(curl -Ls -o /dev/null -w %{url_effective} http://${GERRIT_HOST}/)
            ./src/tungstenfabric/tf-jenkins/infra/gerrit/notify.py \
              --gerrit $url \
              --user $GERRIT_API_USER \
              --password $GERRIT_API_PASSWORD \
              --review $GERRIT_CHANGE_ID \
              --patchset $GERRIT_PATCHSET_NUMBER \
              --branch $GERRIT_BRANCH \
              --message "Updating jenkins-jobs. ${BUILD_URL}"
          fi
      - shell: |
          #!/bin/bash -e
          cd ./src/tungstenfabric/tf-jenkins/jjb
          python3 -m venv .venv
          source .venv/bin/activate
          pip3 install setuptools wheel --upgrade
          pip3 install jenkins-job-builder 
          echo "--------------------------------------------------------------------- test"
          make test
          echo "--------------------------------------------------------------------- update"
          make update
    triggers:
      - gerrit:
          skip-vote:
            successful: true
            failed: true
            unstable: true
            notbuilt: true
          trigger-on:
            - comment-added-contains-event:
                comment-contains-value: '(?i)^(post)$'
            - change-merged-event
          projects:
            - project-compare-type: 'PLAIN'
              project-pattern: 'tungstenfabric/tf-jenkins'
              branches:
                - branch-compare-type: 'ANT'
                  branch-pattern: '**'
