- job:
    name: "update-base-images"
    description: "update-base-images"
    defaults: global-with-creds
    properties:
      - build-discarder:
          num-to-keep: 30
    node: vexxhost
    triggers:
      - timed: 'H H(2-5) 10 * *'
    parameters:
      - choice:
          name: IMAGE_TYPE
          choices:
            - ALL
            - CENTOS7
            - CENTOS8
            - RHEL7
            - RHEL8
            - UBUNTU18
            - UBUNTU20
            - RHCOS45
          description: "Image type for update or ALL(default)"
    scm:
      - tf-jenkins
    builders:
      - shell: |
          echo "DESCRIPTION Image type=$IMAGE_TYPE"
      - description-setter:
          regexp: "DESCRIPTION (.*)"
      - shell: |
          ./src/tungstenfabric/tf-jenkins/infra/vexxhost/update_base_images.sh
