- job:
    name: "update-prepared-images"
    description: "update-prepared-images"
    defaults: global-with-creds
    properties:
      - build-discarder:
          num-to-keep: 30
    node: vexxhost
#    triggers:
#      - timed: 'H H(3-4) * * 1'
    parameters:
      - choice:
          name: IMAGE_TYPE
          choices:
            - ALL
            - CENTOS7
            - CENTOS8
            - RHEL7
            - RHEL8
            - UBUNTU18
            - UBUNTU20
            - RHCOS45
          description: "Image type for update or ALL(default)"
    scm:
      - tf-jenkins
    wrappers:
      - credentials-binding:
          - text:
              credential-id: RHEL_USER
              variable: RHEL_USER
          - text:
              credential-id: RHEL_PASSWORD
              variable: RHEL_PASSWORD
          - text:
              credential-id: RHEL_POOL_ID
              variable: RHEL_POOL_ID
    builders:
      - shell: |
          echo "DESCRIPTION Image type=$IMAGE_TYPE"
      - description-setter:
          regexp: "DESCRIPTION (.*)"
      - shell: |
          ./src/tungstenfabric/tf-jenkins/infra/vexxhost/update_prepared_images.sh
