- name: Create temporary build directory
  tempfile:
    state: directory
    suffix: docker-build
  register: docker_build_dir

- name: Copy syncdocs entrypoint
  template:
    src: "{{ item }}.j2"
    dest: "{{ docker_build_dir.path }}/{{ item }}.sh"
  with_items:
    - entrypoint.sh
    - sync_docs.sh

- name: Copy entrypoint to build directory
  copy:
    src: "Dockerfile"
    dest: "{{ docker_build_dir.path }}/Dockerfile"

- name: Build syncdocs image
  docker_image:
    build:
      path: "{{ docker_build_dir.path }}"
      pull: yes
    name: sync-docs
    source: build
    tag: latest
    force_tag: yes
    force_source: yes
  register: sync-docs

- name: Create syncdocs container
  docker_container:
    name: sync-docs
    image: sync-docs
    restart_policy: unless-stopped
