---

- project:
    name: tungstenfabric
    nightly:
      templates:
        - build-r1912
        - build-r1912-ubi
        - build-r2011-ubi
        - build-r2011-centos
        #- build-r21.3-centos
        - test-unit
        - test-unit-ui
        - k8s-manifests
        - k8s-manifests-ha
        - ansible-k8s
        - ansible-k8s-ha
        - ansible-os
        - ansible-os-ha-ziu
        - juju-k8s
        - juju-os
        #- juju-os-maas
        - juju-os-1912
        - juju-os-2011
        - juju-hybrid-ha-ziu
        - rhosp13-1912
        - rhosp13-2011
        - rhosp13-ha-ziu
        - rhosp16.1-2011
        - rhosp16.1-ha-ziu
        - rhosp16.2-ha
        #- rhosp13-bmc
        #- rhosp16.2-bmc
        - operator
        - operator-ha
        - operator-2011
        # - openshift4-slave01
        # - openshift4-slave04
        - juju-os-not-implemented-targets
        - juju-k8s-not-implemented-targets
        - juju-hybrid-not-implemented-targets
        - rhosp13-os-not-implemented-targets
        - rhosp16-os-not-implemented-targets
        - ansible-os-not-implemented-targets
        - cleanup
      streams:
        build-centos:
          vars:
            DEBUGINFO: TRUE
        build-r1912:
          frequency: 7
          vars:
            DEBUGINFO: TRUE
        build-r1912-ubi:
          frequency: 7
          vars:
            DEBUGINFO: TRUE
        build-r2011-ubi:
          vars:
            DEBUGINFO: TRUE
        build-r2011-centos:
          vars:
            DEBUGINFO: TRUE
        build-r21.3-centos:
          vars:
            DEBUGINFO: TRUE
        # additional schedule for some streams
        ansible-k8s:
          frequency: 7
        juju-os-1912:
          frequency: 7
        rhosp13-1912:
          frequency: 7
        rhosp13-ha-ziu:
          frequency: 7
        operator-2011:
          frequency: 7
        # hack with locks due to lack of resources
        operator-ha:
          lock: group-two-ha
        juju-os-ha-ziu:
          lock: group-two-ha
        juju-k8s-ha:
          lock: group-two-ha
        juju-hybrid-ha:
          lock: group-two-ha
        ansible-os-ha:
          lock: group-one-ha
        ansible-os-ha-ziu:
          lock: group-one-ha
        ansible-k8s-ha:
          frequency: 7
          lock: group-one-ha
        k8s-manifests-ha:
          lock: group-one-ha
        openshift4-slave01:
          vars:
            CONTAINER_REGISTRY: 'tf-nexus.$SLAVE_REGION.$CI_DOMAIN:5102'
            DEPLOYER_CONTAINER_REGISTRY: 'tf-nexus.$SLAVE_REGION.$CI_DOMAIN:5102'
        openshift4-slave04:
          vars:
            CONTAINER_REGISTRY: 'tf-nexus.$SLAVE_REGION.$CI_DOMAIN:5102'
            DEPLOYER_CONTAINER_REGISTRY: 'tf-nexus.$SLAVE_REGION.$CI_DOMAIN:5102'
      jobs:
        publish-centos-nightly:
          job-name: publish
          depends-on:
            - package-centos
        publish-r2011-centos-nightly:
          job-name: publish
          depends-on:
            - package-r2011-centos
          vars:
            TAG_SUFFIX: "-r2011-centos"
            GERRIT_BRANCH: "R2011"
        # to use just built nightly images
        deploy-tf-juju-os-1912:
          # additional deps
          depends-on:
            - package-r1912
        deploy-tf-juju-os-2011:
          # additional deps
          depends-on:
            - package-r2011-centos
        deploy-tf-rhosp13-1912:
          # additional deps
          depends-on:
            - package-deployers-r1912-ubi
        deploy-tf-rhosp13-2011:
          # additional deps
          depends-on:
            - package-deployers-r2011-ubi
        deploy-tf-rhosp16.1-2011:
          # additional deps
          depends-on:
            - package-deployers-r2011-ubi

        #publish-centos-r1912:
        #  job-name: publish
        #  depends-on:
        #    - package-r1912
        #  vars:
        #    TAG_SUFFIX: "-r1912"
        #    PUBLISH_TAGS: "R1912"
        #publish-r21.3-centos-nightly:
        #  job-name: publish
        #  depends-on:
        #    - package-r21.3-centos
        #  vars:
        #    TAG_SUFFIX: "-r21.3-centos"
        #    GERRIT_BRANCH: "R21.3"

        aquascan-ubi-nightly:
          job-name: aquascan
          depends-on:
            - package-ubi8
          vars:
            TAG_SUFFIX: "-ubi8"
      post-jobs:
        publish-centos-stable:
          job-name: publish
        cleanup-workers:
          depends-on:
            - publish-centos-stable
