---

- project:
    name: opensdn-io
    nightly:
      templates:
        - docs-doxygen
        - build-r24.1-centos
        - build-rocky9
        - test-unit
        - test-unit-ui
        - k8s-manifests
        # - k8s-manifests-ha
        # - ansible-k8s
        # - ansible-k8s-ha
        - ansible-os
        - ansible-os-ha
        - ansible-os-tempest
        - ansible-os-vanilla
        - ansible-os-r24.1
        - ansible-os-ha-ziu
        - juju-k8s
        - juju-os
        # - juju-os-ha-ziu
        #- juju-os-maas
        #- juju-hybrid-ha-ziu
        - juju-os-not-implemented-targets
        - juju-k8s-not-implemented-targets
        - juju-hybrid-not-implemented-targets
        - ansible-os-not-implemented-targets
        - cleanup
      streams:
        build-centos:
          vars:
            DEBUGINFO: "TRUE"
        build-r24.1-centos:
         vars:
           DEBUGINFO: "TRUE"
        # additional schedule for some streams
        ansible-k8s:
          frequency: 7
        # hack with locks due to lack of resources
        juju-os-ha-ziu:
          lock: group-two-ha
        juju-k8s-ha:
          lock: group-two-ha
        juju-hybrid-ha:
          lock: group-two-ha
        ansible-os-ha:
          lock: group-one-ha
        ansible-os-ha-ziu:
          lock: group-one-ha
        ansible-k8s-ha:
          frequency: 7
          lock: group-one-ha
        k8s-manifests-ha:
          lock: group-one-ha
      jobs:
        publish-centos-nightly:
          job-name: publish
          depends-on:
            - package-centos

        # to use just built nightly images
        deploy-platform-ansible-os-ha-ziu:
          # additional deps
          depends-on:
            - package-deployers-r24.1-centos
        #deploy-tf-juju-hybrid-ha-ziu:
        #  # additional deps
        #  depends-on:
        #    - package-r24.1-ubi

        #publish-r24.1-centos-nightly:
        #  job-name: publish
        #  depends-on:
        #    - package-r24.1-centos
        #  vars:
        #    TAG_SUFFIX: "-r24.1-centos"
        #    GERRIT_BRANCH: "R24.1"

        publish-rocky9-nightly:
         job-name: publish
         depends-on:
           - package-rocky9
         vars:
           TAG_SUFFIX: "-rocky9"

        #aquascan-ubi-nightly:
        #  job-name: aquascan
        #  depends-on:
        #    - package-ubi8
        #  vars:
        #    TAG_SUFFIX: "-ubi8"
      post-jobs:
        publish-centos-stable:
          job-name: publish
        cleanup-workers:
          depends-on:
            - publish-centos-stable
