---

# cache project
- project:
    names:
      - tungstenfabric/tf-third-party-cache
    post-merge:
      jobs:
        update-caches:

# just build projects
- project:
    names:
      - tungstenfabric/tf-deployers-containers
      - tungstenfabric/tf-openshift-ansible
      - tungstenfabric/tf-java-api
      - tungstenfabric/tf-vijava
      - tungstenfabric/tf-vrouter-java-api
      - tungstenfabric/tf-vro-plugin
      - tungstenfabric/tf-vcenter-plugin
    check:
      templates:
        - build-centos
        - cleanup
    gate:
      templates:
        - build-centos
        - cleanup

# just build projects including ubi8
- project:
    names:
      - tungstenfabric/tf-dpdk
    check:
      templates:
        - build-centos
        - cleanup
    gate:
      templates:
        - build-centos
        - build-ubi8
        - cleanup

# simple checks
- project:
    names:
      - tungstenfabric/tf-vnc
      - tungstenfabric/tf-test
      - tungstenfabric/tf-dev-test
      - tungstenfabric/tf-nova-vif-driver
      - tungstenfabric/tf-heat-plugin
    check:
      templates:
        - ansible-os
        - cleanup
    gate:
      templates:
        - build-ubi8:
            branch: master || R21.4
        - juju-k8s
        - ansible-os
        - operator
        - cleanup

- project:
    names:
      - tungstenfabric/tf-third-party-packages
    check:
      templates:
        - ansible-os
        - cleanup
    gate:
      templates:
        - build-ubi8:
            branch: master || R21.4
        - juju-k8s
        - ansible-os
        - cleanup
    post-merge:
      jobs:
        update-tpc-source-repository-7:
          job-name: update-tpc-source-repository
          job-params:
            TPC_VERSION: el7
        update-tpc-source-repository-8:
          job-name: update-tpc-source-repository
          job-params:
            TPC_VERSION: el8

# simple checks with ubi in gating
- project:
    names:
      - tungstenfabric/tf-packages
    check:
      templates:
        - ansible-os
        - cleanup
    gate:
      templates:
        - build-ubi:
            branch: "!(master || R21.4)"
        - build-ubi8:
            branch: master || R21.4
        - build-centos
        - juju-k8s
        - ansible-os
        - cleanup

- project:
    names:
      - tungstenfabric/tf-third-party
    check:
      templates:
        - ansible-os
        - cleanup
    gate:
      templates:
        - build-ubi:
            branch: "!(master || R21.4)"
        - build-ubi8:
            branch: master || R21.4
        - build-centos
        - juju-k8s
        - ansible-os
        - cleanup
    post-merge:
      jobs:
        update-caches:

# core TF projects with old style UT
- project:
    names:
      - tungstenfabric/tf-controller
      - tungstenfabric/tf-api-client
      - tungstenfabric/tf-common
      - tungstenfabric/tf-analytics
      - tungstenfabric/tf-neutron-plugin
      - tungstenfabric/tf-build
    check:
      templates:
        - test-unit
        - ansible-os
        - cleanup
    gate:
      templates:
        - test-unit
        - build-ubi8:
            branch: master || R21.4
        - juju-k8s
        - ansible-os
        - operator
        - cleanup

# old web UI projects
- project:
    names:
      - tungstenfabric/tf-web-core
      - tungstenfabric/tf-web-controller
    check:
      templates:
        - test-unit-ui
        - ansible-os
        - cleanup
    gate:
      templates:
        - build-ubi:
            branch: "!(master || R21.4)"
        - build-ubi8:
            branch: master || R21.4
        - build-centos
        - cleanup
    post-merge:
      jobs:
        update-caches:

- project:
    names:
      - tungstenfabric/tf-webui-third-party
    check:
      templates:
        - test-unit-ui
        - ansible-os
        - cleanup
    gate:
      templates:
        - build-ubi:
            branch: "!(master || R21.4)"
        - build-ubi8:
            branch: master || R21.4
        - build-centos
        - cleanup

- project:
    name: tungstenfabric/tf-ansible-deployer
    check:
      templates:
        - test-tox-pep8
        - test-tox-py36
        - ansible-k8s
        - ansible-os
        - cleanup
    gate:
      templates:
        - ansible-k8s
        - ansible-os
        - cleanup

- project:
    name: tungstenfabric/tf-kolla-ansible
    check:
      templates:
        - ansible-os
        - cleanup
    gate:
      templates:
        - ansible-os
        - cleanup

- project:
    name: tungstenfabric/tf-container-builder
    check:
      templates:
        - ansible-os
        - test-tox-unit
        - cleanup
    gate:
      templates:
        - build-ubi:
            branch: "!(master || R21.4)"
        - build-ubi8:
            branch: master || R21.4
        - juju-k8s
        - ansible-os
        - operator
        - cleanup
    post-merge:
      jobs:
        update-caches:

- project:
    name: tungstenfabric/tf-vrouter
    check:
      templates:
        - test-unit
        - ansible-os
        - juju-os
        - cleanup
    gate:
      templates:
        - test-unit
        - build-ubi8:
            branch:
              - master
              - R21.4
        - juju-k8s
        - ansible-os
        - cleanup

- project:
    name: tungstenfabric/tf-helm-deployer
    check:
      templates:
        - helm-k8s
        - helm-os
        - cleanup
    gate:
      templates:
        - helm-k8s
        - helm-os
        - cleanup

- project:
    name: tungstenfabric/tf-charms
    streams:
      juju-os-2011:
        voting: false
    check:
      templates:
        - test-tox-pep8
        - juju-k8s
        - juju-os
        - juju-os-2011
        - cleanup
    gate:
      templates:
        - juju-k8s
        - juju-os

- project:
    name: tungstenfabric/tf-tripleo-puppet
    check:
      templates:
        - rhosp13-2011
        - rhosp16.1-2011:
            branch: R.+
        - rhosp16.2:
            branch: master
        - cleanup
    gate:
      templates:
        - rhosp13-2011
        - rhosp16.1-2011:
            branch: R.+
        - rhosp16.2:
            branch: master
        - cleanup

- project:
    name: tungstenfabric/tf-tripleo-heat-templates
    check:
      templates:
        - rhosp13-2011:
            branch: stable/queens
        - rhosp13-1912:
            branch: stable/queens
        - rhosp16.2:
            branch: stable/train
        - cleanup
    gate:
      templates:
        - rhosp13-2011:
            branch: stable/queens
        - rhosp13-1912:
            branch: stable/queens
        - rhosp16.1-2011:
            branch: stable/train
        - rhosp16.2:
            branch: stable/train
        - cleanup

- project:
    name: tungstenfabric/tf-operator
    check:
      templates:
        - operator
        - test-unit-go
        - cleanup
    gate:
      templates:
        - operator
        - cleanup

- project:
    names:
      - tungstenfabric/tf-vcenter-fabric-manager
      - tungstenfabric/tf-vcenter-manager
    check:
      templates:
        - test-unit
        - build-centos
        - cleanup
    gate:
      templates:
        - test-unit
        - build-centos
        - cleanup

- project:
    name: tungstenfabric/tf-deployment-test
    check:
      templates:
        - test-tox-pep8
        - ansible-os
        - cleanup
    gate:
      templates:
        - build-centos
        - juju-k8s
        - ansible-os
        - cleanup

# infra projects

- project:
    name: tungstenfabric/tf-dev-env
    check:
      templates:
        - build-centos
        - ansible-os
        - cleanup
    gate:
      streams:
        build-ubi:
          vars:
            GERRIT_BRANCH: "R2011"
      templates:
        - build-ubi
        - build-ubi8
        - build-centos
        - build-r2011-centos
        - juju-k8s
        - ansible-os
        - cleanup
    post-merge:
      jobs:
        cleanup-tf-dev-sandbox:
        update-caches:

- project:
    name: tungstenfabric/tf-jenkins
    check:
      templates:
        - build-centos
        - operator
        - cleanup
    post-merge:
      jobs:
        update-jenkins-jobs:
        update-caches:

- project:
    name: tungstenfabric/tf-devstack
