---

# This file contains defitions of jobs for each project from review system and for infra projects

# project object
# it may have own full definition of jobs or inclusion of templates with overrides
#
# project keys:
#   name - the name of project from review system
#   names - list of projects (to support forks or migration)
#   check/gate/nightly...: name of predefined pipeline. Check/gate is used for check/gate events.
#                          nightly and other are used to manually run infra jobs

# pipeline contains:
#   templates array to specify templates for this pipeline
#   jobs dictionary with overrides for included templates at stream level
#   streams dictionary with overrides for included templates at job level

# template object may contain any set of jobs but best practice is to use it to one stream.
#
# template keys:
#   name - name of template to refer in pipeline
#   parents - list of template that must be used with this templates. this explicitely defines
#             dependent template to be able to refer in defined jobs to external jobs.
#   jobs - dictionary with jobs for this template
#   streams - dictionary with definitions for streams in this template

# stream is a virtual object to group set of jobs that has common workers/logs/reports/vars
# by default jobs in one stream inherit variables produced by dependent job.
# to be able to use variable of job from different template you have to use 'inherit-keys' property.
#
# stream keys:
#   vars - map of a key:value elements to use them as env vars in the job

# job is a smallest unit of work. it refers to specific job of Jenkins
#
# job keys:
#   job-name - name of real job in jjb(jenkins) to execute. to be able to have several
#              jobs with different parameters we have to to define job with unique name
#              and define real job name as a parameter.
#   stream - identifier to group several jobs as one. it influences to logs colelcting,
#            cleanup jobs (as a stream post hook), inheritance of env vars
#   vars - map of a key:value elements to use them as env vars in the job
#   depends-on - list of jobs that should be finished successfully to run this job.
#                may have inherit-keys list of keys of env vars that can be inherited
#                from non-self stream. by default inheritance of env vars is prohibited
#                for different streams.
#   type - type of the job. possible values: stream-post-hook
#   timeout - timeout in minutes. 180 by default


# TODO: implement 'default' project with cleanup job

# TODO: implement templates for projects with pipelines/templates to reduce copy-paste in each project

- include:
    - templates.yaml
    - templates-ansible.yaml
    - templates-build.yaml
    - templates-helm.yaml
    - templates-juju.yaml
    - templates-k8s-manifests.yaml
    - templates-openshift.yaml
    - templates-operator.yaml
    - templates-rhosp.yaml
    - templates-tests.yaml

- project:
    name: tungstenfabric
    nightly:
      templates:
        - build-r1912
        - build-r1912-ubi
        - build-r2011-ubi
        - build-r2011-centos
        - test-unit
        - test-unit-ui
        - k8s-manifests
        - k8s-manifests-ha
        - ansible-k8s
        - ansible-k8s-ha
        - ansible-os
        - ansible-os-ha-ziu
        - helm-k8s
        - helm-k8s-ha
        - helm-os
        - helm-os-ha
        - juju-k8s
        - juju-k8s-ha
        - juju-os
        - juju-os-maas
        - juju-os-ha-ziu
        - juju-os-1912
        - juju-hybrid
        - rhosp13
        - rhosp13-1912
        - rhosp13-ha-ziu
        - rhosp16
        - rhosp16-ha-ziu
        - rhosp13-bmc
        - juju-os-not-implemented-targets
        - juju-k8s-not-implemented-targets
        - juju-hybrid-not-implemented-targets
        - rhosp13-os-not-implemented-targets
        - rhosp16-os-not-implemented-targets
        - ansible-os-not-implemented-targets
        - openshift-k8s-not-implemented-targets
        - cleanup
      streams:
        build-centos:
          vars:
            DEBUGINFO: TRUE
        build-ubi:
          vars:
            DEBUGINFO: TRUE
        build-r1912:
          vars:
            DEBUGINFO: TRUE
        build-r1912-ubi:
          vars:
            DEBUGINFO: TRUE
        build-r2011-ubi:
          vars:
            DEBUGINFO: TRUE
        build-r2011-centos:
          vars:
            DEBUGINFO: TRUE
        # hack with locks due to lack of resources
        juju-os-ha-ziu:
          lock: juju-ha
        juju-k8s-ha:
          lock: juju-ha
        helm-k8s-ha:
          lock: helm-ha
        helm-os-ha:
          lock: helm-ha
        ansible-os-ha-ziu:
          lock: ansible-ha
        ansible-k8s-ha:
          lock: ansible-ha
        k8s-manifests-ha:
          lock: ansible-ha
      jobs:
        publish-centos-nightly:
          job-name: publish
          depends-on:
            - package-centos
        publish-r2011-centos-nightly:
          job-name: publish
          depends-on:
            - package-r2011-centos
          vars:
            TAG_SUFFIX: "-r2011-centos"
            GERRIT_BRANCH: "R2011"
        # to use just built nightly images
        deploy-tf-juju-os-1912:
          # additional deps
          depends-on:
            - package-r1912
        deploy-tf-rhosp13-1912:
          # additional deps
          depends-on:
            - package-r1912-ubi

        #publish-centos-r1912:
        #  job-name: publish
        #  depends-on:
        #    - package-r1912
        #  vars:
        #    TAG_SUFFIX: "-r1912"
        #    PUBLISH_TAGS: "R1912"

        #publish-centos-r2011:
        #  job-name: publish
        #  depends-on:
        #    - package-r2011-centos
        #  vars:
        #    TAG_SUFFIX: "-r2011-centos"
        #    PUBLISH_TAGS: "R2011"

        aquascan-ubi-nightly:
          job-name: aquascan
          depends-on:
            - package-ubi
          vars:
            TAG_SUFFIX: "-ubi7"
      post-jobs:
        publish-centos-stable:
          job-name: publish
        cleanup-workers:
          depends-on:
            - publish-centos-stable

- project:
    name: stage-repos-centos7
    stage-repos:
      templates:
        - build-centos
        - ansible-os
        - cleanup
      jobs:
        update-stage-repos-centos7:
          job-name: update-stage-repos
          vars:
            REPOS_TYPE: 'centos7'
        prepare-sandbox-centos:
          depends-on:
            - update-stage-repos-centos7
        deploy-platform-ansible-k8s:
          depends-on:
            - update-stage-repos-centos7
        publish-stage-repos-centos7:
          job-name: publish-stage-repos
          vars:
            REPOS_TYPE: 'centos7'
          depends-on:
            - test-sanity-ansible-os
      post-jobs:
        cleanup-workers:

- project:
    name: stage-repos-rhel7
    stage-repos:
      templates:
        - build-ubi
        - rhosp13
        - cleanup
      jobs:
        update-stage-repos-rhel7:
          job-name: update-stage-repos
          vars:
            REPOS_TYPE: 'rhel7'
        prepare-sandbox-ubi:
          depends-on:
            - update-stage-repos-rhel7
        deploy-platform-rhosp13:
          depends-on:
            - update-stage-repos-rhel7
        publish-stage-repos-rhel7:
          job-name: publish-stage-repos
          vars:
            REPOS_TYPE: 'rhel7'
          depends-on:
            - test-sanity-rhosp13
      post-jobs:
        cleanup-workers:

- project:
    name: stage-repos-rhel8
    stage-repos:
      templates:
        - build-ubi
        - rhosp16
        - cleanup
      jobs:
        update-stage-repos-rhel8:
          job-name: update-stage-repos
          vars:
            REPOS_TYPE: 'rhel8'
        prepare-sandbox-ubi:
          depends-on:
            - update-stage-repos-rhel8
        deploy-platform-rhosp16:
          depends-on:
            - update-stage-repos-rhel8
        publish-stage-repos-rhel8:
          job-name: publish-stage-repos
          vars:
            REPOS_TYPE: 'rhel8'
          depends-on:
            - test-sanity-rhosp16
      post-jobs:
        cleanup-workers:

- project:
    name: stage-repos-ubuntu18
    stage-repos:
      templates:
        - build-centos
        - juju-os
        - cleanup
      jobs:
        update-stage-repos-ubuntu18:
          job-name: update-stage-repos
          vars:
            REPOS_TYPE: 'ubuntu18'
        deploy-platform-juju-os:
          depends-on:
            - update-stage-repos-ubuntu18
        publish-stage-repos-ubuntu18:
          job-name: publish-stage-repos
          vars:
            REPOS_TYPE: 'ubuntu18'
          depends-on:
            - test-sanity-juju-os
      post-jobs:
        cleanup-workers:

- project:
    name: tungstenfabric/tf-vnc
    check:
      templates:
        - ansible-os # juju-os
        - cleanup
    gate:
      templates:
        - ansible-k8s
        - ansible-os
        - cleanup

- project:
    name: tungstenfabric/tf-ansible-deployer
    check:
      templates:
        - test-tox-pep8
        - test-tox-py36
        - ansible-k8s
        - ansible-os
        - cleanup
    gate:
      templates:
        - ansible-k8s
        - ansible-os
        - cleanup

- project:
    name: tungstenfabric/tf-kolla-ansible
    check:
      templates:
        - ansible-os
        - cleanup
    gate:
      templates:
        - ansible-os
        - cleanup

- project:
    name: tungstenfabric/tf-deployers-containers
    check:
      templates:
        - build-centos
        - cleanup
    gate:
      templates:
        - build-centos
        - cleanup

- project:
    name: tungstenfabric/tf-container-builder
    check:
      templates:
        - ansible-os # juju-os
        - test-tox-unit
        - cleanup
    gate:
      templates:
        - build-ubi
        - ansible-k8s
        - ansible-os
        - cleanup

- project:
    name: tungstenfabric/tf-controller
    check:
      templates:
        - test-unit
        - ansible-os # juju-os
        - cleanup
    gate:
      templates:
        - test-unit
        - ansible-k8s
        - ansible-os
        - cleanup

- project:
    name: tungstenfabric/tf-api-client
    check:
      templates:
        - test-unit
        - ansible-os # juju-os
        - cleanup
    gate:
      templates:
        - test-unit
        - ansible-k8s
        - ansible-os
        - cleanup

- project:
    name: tungstenfabric/tf-common
    check:
      templates:
        - test-unit
        - ansible-os # juju-os
        - cleanup
    gate:
      templates:
        - test-unit
        - ansible-k8s
        - ansible-os
        - cleanup

- project:
    name: tungstenfabric/tf-vrouter
    check:
      templates:
        - test-unit
        - ansible-os
        - juju-os
        - cleanup
    gate:
      templates:
        - test-unit
        - ansible-k8s
        - ansible-os
        - cleanup

- project:
    name: tungstenfabric/tf-analytics
    check:
      templates:
        - test-unit
        - ansible-os # juju-os
        - cleanup
    gate:
      templates:
        - test-unit
        - ansible-k8s
        - ansible-os
        - cleanup

- project:
    name: tungstenfabric/tf-packages
    check:
      templates:
        - ansible-os # juju-os
        - cleanup
    gate:
      templates:
        - build-ubi
        - ansible-k8s
        - ansible-os
        - cleanup

- project:
    name: tungstenfabric/tf-test
    check:
      templates:
        - ansible-os # juju-os
        - cleanup
    gate:
      templates:
        - ansible-k8s
        - ansible-os
        - cleanup

- project:
    name: tungstenfabric/tf-neutron-plugin
    check:
      templates:
        - test-unit
        - ansible-os # juju-os
        - cleanup
    gate:
      templates:
        - test-unit
        - rhosp13
        - rhosp16
        - ansible-os
        - cleanup

- project:
    name: tungstenfabric/tf-helm-deployer
    check:
      templates:
        - helm-k8s
        - helm-os
        - cleanup
    gate:
      templates:
        - helm-k8s
        - helm-os
        - cleanup

- project:
    name: tungstenfabric/tf-third-party-packages
    check:
      templates:
        - ansible-os # juju-os
        - cleanup
    gate:
      templates:
        - ansible-k8s
        - ansible-os
        - cleanup

- project:
    name: tungstenfabric/tf-third-party
    check:
      templates:
        - ansible-os # juju-os
        - cleanup
    gate:
      templates:
        - build-ubi
        - build-centos
        - ansible-k8s
        - ansible-os
        - cleanup

- project:
    name: tungstenfabric/tf-webui-third-party
    check:
      templates:
        - test-unit-ui
        - ansible-os # juju-os
        - cleanup
    gate:
      templates:
        - build-ubi
        - build-centos
        - cleanup

- project:
    name: tungstenfabric/tf-web-core
    check:
      templates:
        - test-unit-ui
        - ansible-os # juju-os
        - cleanup
    gate:
      templates:
        - build-ubi
        - build-centos
        - cleanup

- project:
    name: tungstenfabric/tf-web-controller
    check:
      templates:
        - test-unit-ui
        - ansible-os # juju-os
        - cleanup
    gate:
      templates:
        - build-ubi
        - build-centos
        - cleanup

- project:
    name: tungstenfabric/tf-charms
    check:
      templates:
        - test-tox-pep8
        - juju-k8s
        - juju-os
        - juju-os-1912
        - cleanup
    gate:
      templates:
        - juju-k8s
        - juju-os

- project:
    name: tungstenfabric/tf-tripleo-puppet
    check:
      templates:
        - rhosp13
        - rhosp16
        - cleanup
    gate:
      templates:
        - rhosp13
        - rhosp16
        - cleanup

- project:
    name: tungstenfabric/tf-tripleo-heat-templates
    branch: stable/queens
    check:
      templates:
        - rhosp13
        - rhosp13-1912
        - cleanup
    gate:
      templates:
        - rhosp13
        - rhosp13-1912
        - cleanup

- project:
    name: tungstenfabric/tf-tripleo-heat-templates
    branch: stable/train
    check:
      templates:
        - rhosp16
        - cleanup
    gate:
      templates:
        - rhosp16
        - cleanup

- project:
    name: tungstenfabric/tf-openshift-ansible
    check:
      templates:
        - openshift
        - cleanup
    gate:
      templates:
        - openshift
        - cleanup

- project:
    name: tungstenfabric/tf-vcenter-fabric-manager
    check:
      templates:
        - test-unit
        - build-centos
        - cleanup
    gate:
      templates:
        - test-unit
        - build-centos
        - cleanup

- project:
    name: tungstenfabric/tf-vcenter-manager
    check:
      templates:
        - test-unit
        - build-centos
        - cleanup
    gate:
      templates:
        - test-unit
        - build-centos
        - cleanup

- project:
    name: tungstenfabric/tf-vcenter-plugin
    check:
      templates:
        - build-centos
        - cleanup
    gate:
      templates:
        - build-centos
        - cleanup

- project:
    name: tungstenfabric/tf-build
    check:
      templates:
        - test-unit
        - ansible-os # juju-os
        - cleanup
    gate:
      templates:
        - build-ubi
        - build-centos
        - ansible-k8s
        - ansible-os
        - cleanup

- project:
    name: tungstenfabric/tf-deployment-test
    check:
      templates:
        - test-tox-pep8
        - ansible-os # juju-os
        - cleanup
    gate:
      templates:
        - build-centos
        - ansible-k8s
        - ansible-os
        - cleanup

# infra projects

- project:
    name: tungstenfabric/tf-dev-test
    check:
      templates:
        - ansible-os # juju-os
        - cleanup
    gate:
      templates:
        - build-centos
        - ansible-k8s
        - ansible-os
        - cleanup

- project:
    name: tungstenfabric/tf-dev-env
    check:
      templates:
        - build-centos
        - ansible-os # juju-os
        - cleanup
    gate:
      templates:
        - build-ubi
        - build-centos
        - ansible-k8s
        - ansible-os
        - cleanup

- project:
    name: tungstenfabric/tf-jenkins
    check:
      templates:
        - ansible-os
        - juju-os
        - rhosp13
        - rhosp16
        - cleanup
