---

- project:
    name: tungstenfabric/tf-vnc
    check:
      templates:
        - ansible-os # juju-os
        - cleanup
    gate:
      templates:
        - ansible-k8s
        - ansible-os
        - cleanup

- project:
    name: tungstenfabric/tf-ansible-deployer
    check:
      templates:
        - test-tox-pep8
        - test-tox-py36
        - ansible-k8s
        - ansible-os
        - cleanup
    gate:
      templates:
        - ansible-k8s
        - ansible-os
        - cleanup

- project:
    name: tungstenfabric/tf-kolla-ansible
    check:
      templates:
        - ansible-os
        - cleanup
    gate:
      templates:
        - ansible-os
        - cleanup

- project:
    name: tungstenfabric/tf-deployers-containers
    check:
      templates:
        - build-centos
        - cleanup
    gate:
      templates:
        - build-centos
        - cleanup

- project:
    name: tungstenfabric/tf-container-builder
    check:
      templates:
        - ansible-os # juju-os
        - test-tox-unit
        - cleanup
    gate:
      templates:
        - build-ubi
        - ansible-k8s
        - ansible-os
        - cleanup

- project:
    name: tungstenfabric/tf-controller
    check:
      templates:
        - test-unit
        - ansible-os # juju-os
        - cleanup
    gate:
      templates:
        - test-unit
        - ansible-k8s
        - ansible-os
        - cleanup

- project:
    name: tungstenfabric/tf-api-client
    check:
      templates:
        - test-unit
        - ansible-os # juju-os
        - cleanup
    gate:
      templates:
        - test-unit
        - ansible-k8s
        - ansible-os
        - cleanup

- project:
    name: tungstenfabric/tf-common
    check:
      templates:
        - test-unit
        - ansible-os # juju-os
        - cleanup
    gate:
      templates:
        - test-unit
        - ansible-k8s
        - ansible-os
        - cleanup

- project:
    name: tungstenfabric/tf-vrouter
    check:
      templates:
        - test-unit
        - ansible-os
        - juju-os
        - cleanup
    gate:
      templates:
        - test-unit
        - ansible-k8s
        - ansible-os
        - cleanup

- project:
    name: tungstenfabric/tf-analytics
    check:
      templates:
        - test-unit
        - ansible-os # juju-os
        - cleanup
    gate:
      templates:
        - test-unit
        - ansible-k8s
        - ansible-os
        - cleanup

- project:
    name: tungstenfabric/tf-packages
    check:
      templates:
        - ansible-os # juju-os
        - cleanup
    gate:
      templates:
        - build-ubi
        - ansible-k8s
        - ansible-os
        - cleanup

- project:
    name: tungstenfabric/tf-test
    check:
      templates:
        - ansible-os # juju-os
        - cleanup
    gate:
      templates:
        - ansible-k8s
        - ansible-os
        - cleanup

- project:
    name: tungstenfabric/tf-neutron-plugin
    check:
      templates:
        - test-unit
        - ansible-os # juju-os
        - cleanup
    gate:
      templates:
        - test-unit
        - rhosp13
        - rhosp16
        - ansible-os
        - cleanup

- project:
    name: tungstenfabric/tf-helm-deployer
    check:
      templates:
        - helm-k8s
        - helm-os
        - cleanup
    gate:
      templates:
        - helm-k8s
        - helm-os
        - cleanup

- project:
    name: tungstenfabric/tf-third-party-packages
    check:
      templates:
        - ansible-os # juju-os
        - cleanup
    gate:
      templates:
        - ansible-k8s
        - ansible-os
        - cleanup

- project:
    name: tungstenfabric/tf-third-party
    check:
      templates:
        - ansible-os # juju-os
        - cleanup
    gate:
      templates:
        - build-ubi
        - build-centos
        - ansible-k8s
        - ansible-os
        - cleanup

- project:
    name: tungstenfabric/tf-webui-third-party
    check:
      templates:
        - test-unit-ui
        - ansible-os # juju-os
        - cleanup
    gate:
      templates:
        - build-ubi
        - build-centos
        - cleanup

- project:
    name: tungstenfabric/tf-web-core
    check:
      templates:
        - test-unit-ui
        - ansible-os # juju-os
        - cleanup
    gate:
      templates:
        - build-ubi
        - build-centos
        - cleanup

- project:
    name: tungstenfabric/tf-web-controller
    check:
      templates:
        - test-unit-ui
        - ansible-os # juju-os
        - cleanup
    gate:
      templates:
        - build-ubi
        - build-centos
        - cleanup

- project:
    name: tungstenfabric/tf-charms
    check:
      streams:
        juju-os-1912:
          voting: false
      templates:
        - test-tox-pep8
        - juju-k8s
        - juju-os
        - juju-os-1912
        - cleanup
    gate:
      templates:
        - juju-k8s
        - juju-os

- project:
    name: tungstenfabric/tf-tripleo-puppet
    check:
      templates:
        - rhosp13
        - rhosp16
        - cleanup
    gate:
      templates:
        - rhosp13
        - rhosp16
        - cleanup

- project:
    name: tungstenfabric/tf-tripleo-heat-templates
    branch: stable/queens
    check:
      templates:
        - rhosp13
        - rhosp13-1912
        - cleanup
    gate:
      templates:
        - rhosp13
        - rhosp13-1912
        - cleanup

- project:
    name: tungstenfabric/tf-tripleo-heat-templates
    branch: stable/train
    check:
      templates:
        - rhosp16
        - cleanup
    gate:
      templates:
        - rhosp16
        - cleanup

- project:
    name: tungstenfabric/tf-openshift-ansible

- project:
    name: tungstenfabric/tf-operator
    check:
      templates:
        - operator
        - operator-ha
        - cleanup
    gate:
      templates:
        - operator
        - operator-ha
        - cleanup

- project:
    name: tungstenfabric/tf-vcenter-fabric-manager
    check:
      templates:
        - test-unit
        - build-centos
        - cleanup
    gate:
      templates:
        - test-unit
        - build-centos
        - cleanup

- project:
    name: tungstenfabric/tf-vcenter-manager
    check:
      templates:
        - test-unit
        - build-centos
        - cleanup
    gate:
      templates:
        - test-unit
        - build-centos
        - cleanup

- project:
    name: tungstenfabric/tf-vcenter-plugin
    check:
      templates:
        - build-centos
        - cleanup
    gate:
      templates:
        - build-centos
        - cleanup

- project:
    name: tungstenfabric/tf-build
    check:
      templates:
        - test-unit
        - ansible-os # juju-os
        - cleanup
    gate:
      templates:
        - build-ubi
        - build-centos
        - ansible-k8s
        - ansible-os
        - cleanup

- project:
    name: tungstenfabric/tf-deployment-test
    check:
      templates:
        - test-tox-pep8
        - ansible-os # juju-os
        - cleanup
    gate:
      templates:
        - build-centos
        - ansible-k8s
        - ansible-os
        - cleanup

# infra projects

- project:
    name: tungstenfabric/tf-dev-test
    check:
      templates:
        - ansible-os # juju-os
        - cleanup
    gate:
      templates:
        - build-centos
        - ansible-k8s
        - ansible-os
        - cleanup

- project:
    name: tungstenfabric/tf-dev-env
    check:
      templates:
        - build-centos
        - ansible-os # juju-os
        - cleanup
    gate:
      templates:
        - build-ubi
        - build-centos
        - build-r2011-centos
        - ansible-k8s
        - ansible-os
        - cleanup

- project:
    name: tungstenfabric/tf-jenkins
    check:
      templates:
        - ansible-os
        - juju-os
        - operator
        - rhosp13
        - rhosp16
        - cleanup

- project:
    name: tungstenfabric/tf-operator
