---

- project:
    name: init-repos-centos7
    init-repos:
      templates:
        - cleanup
      jobs:
        update-stage-repos-centos7:
          job-name: update-stage-repos
          timeout: 600
          vars:
            REPOS_TYPE: 'centos7'
        publish-stage-repos-centos7:
          job-name: publish-stage-repos
          vars:
            REPOS_TYPE: 'centos7'
          depends-on:
            - update-stage-repos-centos7

- project:
    name: init-repos-rocky9
    init-repos:
      templates:
        - cleanup
      jobs:
        update-stage-repos-rocky9:
          job-name: update-stage-repos
          timeout: 600
          vars:
            REPOS_TYPE: 'rocky9'
        publish-stage-repos-rocky9:
          job-name: publish-stage-repos
          vars:
            REPOS_TYPE: 'rocky9'
          depends-on:
            - update-stage-repos-rocky9

- project:
    name: init-repos-ubuntu
    init-repos:
      templates:
        - cleanup
      jobs:
        update-stage-repos-ubuntu:
          job-name: update-stage-repos
          timeout: 600
          vars:
            REPOS_TYPE: 'ubuntu'
        publish-stage-repos-ubuntu:
          job-name: publish-stage-repos
          vars:
            REPOS_TYPE: 'ubuntu'
          depends-on:
            - update-stage-repos-ubuntu

- project:
    name: stage-repos-centos7
    stage-repos:
      templates:
        - build-centos
        - ansible-os
        - ansible-k8s
        - cleanup
      jobs:
        update-stage-repos-centos7:
          job-name: update-stage-repos
          timeout: 600
          vars:
            REPOS_TYPE: 'centos7'
        prepare-sandbox-centos:
          depends-on:
            - update-stage-repos-centos7
          vars:
            DEVENV_TAG: stage-centos7-$RANDOM
        deploy-platform-ansible-os:
          depends-on:
            - update-stage-repos-centos7
        deploy-platform-ansible-k8s:
          depends-on:
            - update-stage-repos-centos7
        publish-stage-repos-centos7:
          job-name: publish-stage-repos
          vars:
            REPOS_TYPE: 'centos7'
          depends-on:
            - test-sanity-ansible-os
            - test-sanity-ansible-k8s

#TODO: add checks for deployment with ubuntu20
- project:
    name: stage-repos-ubuntu
    stage-repos:
      templates:
        - build-centos
        - juju-os
        - cleanup
      jobs:
        update-stage-repos-ubuntu:
          job-name: update-stage-repos
          timeout: 600
          vars:
            REPOS_TYPE: 'ubuntu'
        prepare-sandbox-centos:
          depends-on:
            - update-stage-repos-ubuntu
        deploy-platform-juju-os:
          depends-on:
            - update-stage-repos-ubuntu
        publish-stage-repos-ubuntu:
          job-name: publish-stage-repos
          vars:
            REPOS_TYPE: 'ubuntu'
          depends-on:
            - test-sanity-juju-os
