---

- project:
    name: init-repos-centos7
    init-repos:
      templates:
        - cleanup
      jobs:
        update-stage-repos-centos7:
          job-name: update-stage-repos
          timeout: 600
          vars:
            REPOS_TYPE: 'centos7'
        publish-stage-repos-centos7:
          job-name: publish-stage-repos
          vars:
            REPOS_TYPE: 'centos7'
          depends-on:
            - update-stage-repos-centos7

- project:
    name: init-repos-rhel7
    init-repos:
      templates:
        - cleanup
      jobs:
        update-stage-repos-rhel7:
          job-name: update-stage-repos
          timeout: 600
          vars:
            REPOS_TYPE: 'rhel7'
        update-stage-images-rhel7:
          job-name: update-stage-images
          vars:
            CONTAINER_REGISTRY: 'tf-mirrors.$SLAVE_REGION.$CI_DOMAIN:5005'
            REPOS_TYPE: 'rhel7'
        publish-stage-repos-rhel7:
          job-name: publish-stage-repos
          vars:
            REPOS_TYPE: 'rhel7'
          depends-on:
            - update-stage-repos-rhel7
        publish-stage-images-rhel7:
          job-name: publish-stage-images
          vars:
            CONTAINER_REGISTRY: 'tf-mirrors.$SLAVE_REGION.$CI_DOMAIN:5005'
            REPOS_TYPE: 'rhel7'
          depends-on:
            - update-stage-images-rhel7

- project:
    name: init-repos-rhel8
    init-repos:
      templates:
        - cleanup
      jobs:
        update-stage-repos-rhel8:
          job-name: update-stage-repos
          timeout: 600
          vars:
            REPOS_TYPE: 'rhel8'
        update-stage-images-rhel8:
          job-name: update-stage-images
          vars:
            CONTAINER_REGISTRY: 'tf-mirrors.$SLAVE_REGION.$CI_DOMAIN:5005'
            REPOS_TYPE: 'rhel8'
        publish-stage-repos-rhel8:
          job-name: publish-stage-repos
          vars:
            REPOS_TYPE: 'rhel8'
          depends-on:
            - update-stage-repos-rhel8
        publish-stage-images-rhel8:
          job-name: publish-stage-images
          vars:
            CONTAINER_REGISTRY: 'tf-mirrors.$SLAVE_REGION.$CI_DOMAIN:5005'
            REPOS_TYPE: 'rhel8'
          depends-on:
            - update-stage-images-rhel8

- project:
    name: init-repos-ubuntu
    init-repos:
      templates:
        - cleanup
      jobs:
        update-stage-repos-ubuntu:
          job-name: update-stage-repos
          timeout: 600
          vars:
            REPOS_TYPE: 'ubuntu'
        publish-stage-repos-ubuntu:
          job-name: publish-stage-repos
          vars:
            REPOS_TYPE: 'ubuntu'
          depends-on:
            - update-stage-repos-ubuntu


- project:
    name: stage-repos-centos7
    stage-repos:
      templates:
        - build-centos
        - ansible-os
        - ansible-k8s
        - cleanup
      jobs:
        update-stage-repos-centos7:
          job-name: update-stage-repos
          timeout: 600
          vars:
            REPOS_TYPE: 'centos7'
        prepare-sandbox-centos:
          depends-on:
            - update-stage-repos-centos7
          vars:
            DEVENV_TAG: stage-centos7-$RANDOM
        deploy-platform-ansible-os:
          depends-on:
            - update-stage-repos-centos7
        deploy-platform-ansible-k8s:
          depends-on:
            - update-stage-repos-centos7
        publish-stage-repos-centos7:
          job-name: publish-stage-repos
          vars:
            REPOS_TYPE: 'centos7'
          depends-on:
            - test-sanity-ansible-os
            - test-sanity-ansible-k8s

- project:
    name: stage-repos-rhel7
    stage-repos:
      templates:
        - build-ubi
        - rhosp13
        - cleanup
      streams:
        rhosp13:
          vars:
            OPENSTACK_CONTAINER_TAG: '13.0-stage'
        build-ubi:
          vars:
            LINUX_DISTR_VER: 'stage'
      jobs:
        update-stage-repos-rhel7:
          job-name: update-stage-repos
          timeout: 600
          vars:
            REPOS_TYPE: 'rhel7'
        update-stage-images-rhel7:
          job-name: update-stage-images
          vars:
            CONTAINER_REGISTRY: 'tf-mirrors.$SLAVE_REGION.$CI_DOMAIN:5005'
            REPOS_TYPE: 'rhel7'
        prepare-sandbox-ubi:
          # it needs images job in deps cause contrail-general-base is based on clean ubi image
          depends-on:
            - update-stage-repos-rhel7
            - update-stage-images-rhel7
          vars:
            DEVENV_TAG: stage-rhel7-$RANDOM
        deploy-platform-rhosp13:
          depends-on:
            - update-stage-repos-rhel7
            - update-stage-images-rhel7
        publish-stage-repos-rhel7:
          job-name: publish-stage-repos
          vars:
            REPOS_TYPE: 'rhel7'
          depends-on:
            - test-sanity-rhosp13
        publish-stage-images-rhel7:
          job-name: publish-stage-images
          vars:
            CONTAINER_REGISTRY: 'tf-mirrors.$SLAVE_REGION.$CI_DOMAIN:5005'
            REPOS_TYPE: 'rhel7'
          depends-on:
            - test-sanity-rhosp13

- project:
    name: stage-repos-rhel8
    stage-repos:
      templates:
        - build-ubi
        - rhosp16
        - cleanup
      streams:
        rhosp16:
          vars:
            OPENSTACK_CONTAINER_TAG: '16.1-stage'
      jobs:
        update-stage-repos-rhel8:
          job-name: update-stage-repos
          timeout: 600
          vars:
            REPOS_TYPE: 'rhel8'
        update-stage-images-rhel8:
          job-name: update-stage-images
          vars:
            CONTAINER_REGISTRY: 'tf-mirrors.$SLAVE_REGION.$CI_DOMAIN:5005'
            REPOS_TYPE: 'rhel8'
        prepare-sandbox-ubi:
          # it needs images job in deps cause contrail-general-base is based on clean ubi image
          depends-on:
            - update-stage-repos-rhel8
            - update-stage-images-rhel8
          vars:
            DEVENV_TAG: stage-rhel8-$RANDOM
        deploy-platform-rhosp16:
          depends-on:
            - update-stage-repos-rhel8
            - update-stage-images-rhel8
        publish-stage-repos-rhel8:
          job-name: publish-stage-repos
          vars:
            REPOS_TYPE: 'rhel8'
          depends-on:
            - test-sanity-rhosp16
        publish-stage-images-rhel8:
          job-name: publish-stage-images
          vars:
            CONTAINER_REGISTRY: 'tf-mirrors.$SLAVE_REGION.$CI_DOMAIN:5005'
            REPOS_TYPE: 'rhel8'
          depends-on:
            - test-sanity-rhosp16

#TODO: add checks for deployment with ubuntu20
- project:
    name: stage-repos-ubuntu
    stage-repos:
      templates:
        - build-centos
        - juju-os
        - cleanup
      jobs:
        update-stage-repos-ubuntu:
          job-name: update-stage-repos
          timeout: 600
          vars:
            REPOS_TYPE: 'ubuntu'
        prepare-sandbox-centos:
          depends-on:
            - update-stage-repos-ubuntu
        deploy-platform-juju-os:
          depends-on:
            - update-stage-repos-ubuntu
        publish-stage-repos-ubuntu:
          job-name: publish-stage-repos
          vars:
            REPOS_TYPE: 'ubuntu'
          depends-on:
            - test-sanity-juju-os
