---

- project:
    name: init-repos-centos7
    init-repos:
      templates:
        - cleanup
      jobs:
        update-stage-repos-centos7:
          job-name: update-stage-repos
          timeout: 600
          vars:
            REPOS_TYPE: 'centos7'
        publish-stage-repos-centos7:
          job-name: publish-stage-repos
          vars:
            REPOS_TYPE: 'centos7'
          depends-on:
            - update-stage-repos-centos7

# - project:
#     name: init-repos-rhel7
#     init-repos:
#       templates:
#         - cleanup
#       jobs:
#         update-stage-repos-rhel7:
#           job-name: update-stage-repos
#           timeout: 600
#           vars:
#             REPOS_TYPE: 'rhel7'
#         update-stage-images-rhel7:
#           job-name: update-stage-images
#           vars:
#             CONTAINER_REGISTRY: 'tf-mirrors.$SLAVE_REGION.$CI_DOMAIN:5005'
#             REPOS_TYPE: 'rhel7'
#         publish-stage-repos-rhel7:
#           job-name: publish-stage-repos
#           vars:
#             REPOS_TYPE: 'rhel7'
#           depends-on:
#             - update-stage-repos-rhel7
#         publish-stage-images-rhel7:
#           job-name: publish-stage-images
#           vars:
#             CONTAINER_REGISTRY: 'tf-mirrors.$SLAVE_REGION.$CI_DOMAIN:5005'
#             REPOS_TYPE: 'rhel7'
#           depends-on:
#             - update-stage-images-rhel7

# - project:
#     name: init-repos-rhel82
#     init-repos:
#       templates:
#         - cleanup
#       jobs:
#         update-stage-repos-rhel82:
#           job-name: update-stage-repos
#           timeout: 600
#           vars:
#             REPOS_TYPE: 'rhel82'
#         update-stage-images-rhel82:
#           job-name: update-stage-images
#           vars:
#             CONTAINER_REGISTRY: 'tf-mirrors.$SLAVE_REGION.$CI_DOMAIN:5005'
#             REPOS_TYPE: 'rhel82'
#         publish-stage-repos-rhel82:
#           job-name: publish-stage-repos
#           vars:
#             REPOS_TYPE: 'rhel82'
#           depends-on:
#             - update-stage-repos-rhel82
#         publish-stage-images-rhel82:
#           job-name: publish-stage-images
#           vars:
#             CONTAINER_REGISTRY: 'tf-mirrors.$SLAVE_REGION.$CI_DOMAIN:5005'
#             REPOS_TYPE: 'rhel82'
#           depends-on:
#             - update-stage-images-rhel82

# - project:
#     name: init-repos-rhel84
#     init-repos:
#       templates:
#         - cleanup
#       jobs:
#         update-stage-repos-rhel84:
#           job-name: update-stage-repos
#           timeout: 600
#           vars:
#             REPOS_TYPE: 'rhel84'
#         update-stage-images-rhel84:
#           job-name: update-stage-images
#           vars:
#             CONTAINER_REGISTRY: 'tf-mirrors.$SLAVE_REGION.$CI_DOMAIN:5005'
#             REPOS_TYPE: 'rhel84'
#         publish-stage-repos-rhel84:
#           job-name: publish-stage-repos
#           vars:
#             REPOS_TYPE: 'rhel84'
#           depends-on:
#             - update-stage-repos-rhel84
#         publish-stage-images-rhel84:
#           job-name: publish-stage-images
#           vars:
#             CONTAINER_REGISTRY: 'tf-mirrors.$SLAVE_REGION.$CI_DOMAIN:5005'
#             REPOS_TYPE: 'rhel84'
#           depends-on:
#             - update-stage-images-rhel84


- project:
    name: init-repos-ubuntu
    init-repos:
      templates:
        - cleanup
      jobs:
        update-stage-repos-ubuntu:
          job-name: update-stage-repos
          timeout: 600
          vars:
            REPOS_TYPE: 'ubuntu'
        publish-stage-repos-ubuntu:
          job-name: publish-stage-repos
          vars:
            REPOS_TYPE: 'ubuntu'
          depends-on:
            - update-stage-repos-ubuntu


- project:
    name: stage-repos-centos7
    stage-repos:
      templates:
        - build-centos
        - ansible-os
        - ansible-k8s
        - cleanup
      jobs:
        update-stage-repos-centos7:
          job-name: update-stage-repos
          timeout: 600
          vars:
            REPOS_TYPE: 'centos7'
        prepare-sandbox-centos:
          depends-on:
            - update-stage-repos-centos7
          vars:
            DEVENV_TAG: stage-centos7-$RANDOM
        deploy-platform-ansible-os:
          depends-on:
            - update-stage-repos-centos7
        deploy-platform-ansible-k8s:
          depends-on:
            - update-stage-repos-centos7
        publish-stage-repos-centos7:
          job-name: publish-stage-repos
          vars:
            REPOS_TYPE: 'centos7'
          depends-on:
            - test-sanity-ansible-os
            - test-sanity-ansible-k8s

- project:
    name: stage-repos-centos8
    stage-repos:
      templates:
        # - build-ubi8
        # - rhosp16.2
        - cleanup
      jobs:
        update-stage-repos-centos8:
          job-name: update-stage-repos
          timeout: 600
          vars:
            REPOS_TYPE: 'centos8'
        # prepare-sandbox-centos:
        #   depends-on:
        #     - update-stage-repos-centos8
        #   vars:
        #     DEVENV_TAG: stage-centos8-$RANDOM
        # deploy-platform-rhosp16.2:
        #   depends-on:
        #     - update-stage-repos-centos8
        publish-stage-repos-centos8:
          job-name: publish-stage-repos
          vars:
            REPOS_TYPE: 'centos8'
          depends-on:
            - update-stage-repos-centos8
          #   - test-sanity-rhosp16.2

# - project:
#     name: stage-repos-rhel7
#     stage-repos:
#       templates:
#         - build-ubi
#         - rhosp13-2011
#         - cleanup
#       streams:
#         rhosp13-2011:
#           vars:
#             OPENSTACK_CONTAINER_TAG: '13.0-stage'
#         build-ubi:
#           vars:
#             LINUX_DISTR_VER: 'stage'
#             GERRIT_BRANCH: "R2011"
#       jobs:
#         update-stage-repos-rhel7:
#           job-name: update-stage-repos
#           timeout: 600
#           vars:
#             REPOS_TYPE: 'rhel7'
#         update-stage-images-rhel7:
#           job-name: update-stage-images
#           vars:
#             CONTAINER_REGISTRY: 'tf-mirrors.$SLAVE_REGION.$CI_DOMAIN:5005'
#             REPOS_TYPE: 'rhel7'
#         prepare-sandbox-ubi:
#           # it needs images job in deps cause contrail-general-base is based on clean ubi image
#           depends-on:
#             - update-stage-repos-rhel7
#             - update-stage-images-rhel7
#           vars:
#             DEVENV_TAG: stage-rhel7-$RANDOM
#         deploy-platform-rhosp13-2011:
#           depends-on:
#             - update-stage-repos-rhel7
#             - update-stage-images-rhel7
#         publish-stage-repos-rhel7:
#           job-name: publish-stage-repos
#           vars:
#             REPOS_TYPE: 'rhel7'
#           depends-on:
#             - test-sanity-rhosp13-2011
#         publish-stage-images-rhel7:
#           job-name: publish-stage-images
#           vars:
#             CONTAINER_REGISTRY: 'tf-mirrors.$SLAVE_REGION.$CI_DOMAIN:5005'
#             REPOS_TYPE: 'rhel7'
#           depends-on:
#             - test-sanity-rhosp13-2011

# - project:
#     name: stage-repos-rhel82
#     stage-repos:
#       templates:
#         - rhosp16.1-2011
#         - cleanup
#       streams:
#         rhosp16.1-2011:
#           vars:
#             OPENSTACK_CONTAINER_TAG: '16.1-stage'
#       jobs:
#         update-stage-repos-rhel82:
#           job-name: update-stage-repos
#           timeout: 600
#           vars:
#             REPOS_TYPE: 'rhel82'
#         update-stage-images-rhel82:
#           job-name: update-stage-images
#           vars:
#             CONTAINER_REGISTRY: 'tf-mirrors.$SLAVE_REGION.$CI_DOMAIN:5005'
#             REPOS_TYPE: 'rhel82'
#         deploy-platform-rhosp16.1-2011:
#           job-name: deploy-platform-rhosp16
#           depends-on:
#             - update-stage-repos-rhel82
#             - update-stage-images-rhel82
#         publish-stage-repos-rhel82:
#           job-name: publish-stage-repos
#           vars:
#             REPOS_TYPE: 'rhel82'
#           depends-on:
#             - test-sanity-rhosp16.1-2011
#         publish-stage-images-rhel82:
#           job-name: publish-stage-images
#           vars:
#             CONTAINER_REGISTRY: 'tf-mirrors.$SLAVE_REGION.$CI_DOMAIN:5005'
#             REPOS_TYPE: 'rhel82'
#           depends-on:
#             - test-sanity-rhosp16.1-2011

# - project:
#     name: stage-repos-rhel84
#     stage-repos:
#       templates:
#         - rhosp16.2
#         - cleanup
#       streams:
#         rhosp16.2:
#           vars:
#             OPENSTACK_CONTAINER_TAG: '16.2-stage'
#       jobs:
#         update-stage-repos-rhel84:
#           job-name: update-stage-repos
#           timeout: 600
#           vars:
#             REPOS_TYPE: 'rhel84'
#         update-stage-images-rhel84:
#           job-name: update-stage-images
#           vars:
#             CONTAINER_REGISTRY: 'tf-mirrors.$SLAVE_REGION.$CI_DOMAIN:5005'
#             REPOS_TYPE: 'rhel84'
#         prepare-sandbox-ubi8:
#           # it needs images job in deps cause contrail-general-base is based on clean ubi image
#           depends-on:
#             - update-stage-repos-rhel84
#             - update-stage-images-rhel84
#           vars:
#             DEVENV_TAG: stage-rhel84-$RANDOM
#         deploy-platform-rhosp16.2:
#           job-name: deploy-platform-rhosp16
#           depends-on:
#             - update-stage-repos-rhel84
#             - update-stage-images-rhel84
#         publish-stage-repos-rhel84:
#           job-name: publish-stage-repos
#           vars:
#             REPOS_TYPE: 'rhel84'
#           depends-on:
#             - test-sanity-rhosp16.2
#         publish-stage-images-rhel84:
#           job-name: publish-stage-images
#           vars:
#             CONTAINER_REGISTRY: 'tf-mirrors.$SLAVE_REGION.$CI_DOMAIN:5005'
#             REPOS_TYPE: 'rhel84'
#           depends-on:
#             - test-sanity-rhosp16.2

#TODO: add checks for deployment with ubuntu20
- project:
    name: stage-repos-ubuntu
    stage-repos:
      templates:
        - build-centos
        - juju-os
        - cleanup
      jobs:
        update-stage-repos-ubuntu:
          job-name: update-stage-repos
          timeout: 600
          vars:
            REPOS_TYPE: 'ubuntu'
        prepare-sandbox-centos:
          depends-on:
            - update-stage-repos-ubuntu
        deploy-platform-juju-os:
          depends-on:
            - update-stage-repos-ubuntu
        publish-stage-repos-ubuntu:
          job-name: publish-stage-repos
          vars:
            REPOS_TYPE: 'ubuntu'
          depends-on:
            - test-sanity-juju-os
