---

# 1. run after all stream jobs if any of stream jobs was run
# 2. shouldn't be included into report
# 3. should not dictate how to wait - wait_for_deps should exit on first fail and do not wait for all
#      collect-logs-and-cleanup-k8s-manifests:
#        type: stream-post-hook

- template:
    name: cleanup
    post-jobs:
      cleanup-workers:
