---

- template:
    name: openshift
    streams:
      openshift:
        voting: False
        vars:
          TAG_SUFFIX: "-ubi7"
          MONITORING_DEPLOY_TARGET: AIO
          MONITORING_DEPLOYER: openshift
          MONITORING_ORCHESTRATOR: k8s
          RHEL_OPENSHIFT_REGISTRY: rhel7-mirrors.tf-jenkins.progmaticlab.com:5000
    parents:
      - build-ubi
    jobs:
      deploy-platform-openshift:
        stream: openshift
        vars:
          ENVIRONMENT_OS: rhel7
      deploy-tf-openshift:
        stream: openshift
        depends-on:
          - deploy-platform-openshift
          - package-ubi
      test-sanity-openshift:
        job-name: test-sanity
        stream: openshift
        depends-on:
          - deploy-tf-openshift
      collect-logs-and-cleanup-openshift:
        job-name: collect-logs-and-cleanup
        stream: openshift
        type: stream-post-hook
        depends-on:
          - deploy-platform-openshift
          - deploy-tf-openshift
          - test-sanity-openshift

- template:
    name: openshift-k8s-not-implemented-targets
    streams:
      openshift-k8s-not-implemented-targets:
        vars:
          MONITORING_DEPLOY_TARGET: HA
          MONITORING_DEPLOYER: openshift
          MONITORING_ORCHESTRATOR: k8s
