---
- template:
    name: build-ubi8-juniper
    streams:
      build-ubi8-englab:
        vars:
          ENVIRONMENT_OS: "rhel84"
          LINUX_DISTR: "ubi8-mirror.englab.juniper.net:5005/ubi8"
          LINUX_DISTR_VER: "8.4"
          TAG_SUFFIX: "-ubi8"
          OPENSTACK_CONTAINER_REGISTRY: "svl-artifactory.juniper.net/contrail-ubi8"
          CONTAINER_REGISTRY: "svl-artifactory.juniper.net/contrail-ubi8"
          REGISTRY_CONTAINER_NAME: 'svl-artifactory'
          #It should be changed.
          CONTRAIL_CONTAINER_TAG: "master-$(date +%Y%m%d)-ubi8"
          SITE_MIRROR: "http://10.87.92.5/"
          CONTRAIL_PARALLEL_BUILD: "false"
          JUMPHOST: juniperlab
    jobs:
      prepare-sandbox-ubi8-juniper:
        # it creates worker
        job-name: build-prepare-sandbox
        stream: build-ubi8-juniper
        vars:
          PUBLISH_TYPE: stable
      fetch-sources-ubi8-juniper:
        job-name: build-fetch-sources
        stream: build-ubi8-juniper
        depends-on:
          - prepare-sandbox-ubi8-juniper
      configure-ubi8-juniper:
        job-name: build-configure
        stream: build-ubi8-juniper
        depends-on:
          - fetch-sources-ubi8-juniper
      package-deployers-ubi8-juniper:
        job-name: build-package-deployers
        stream: build-ubi8-juniper
        depends-on:
          - configure-ubi8-juniper
      compile-ubi8-juniper:
        job-name: build-compile
        stream: build-ubi8-juniper
        depends-on:
          - package-deployers-ubi8-juniper
      package-ubi8-juniper:
        job-name: build-package
        stream: build-ubi8-juniper
        depends-on:
          - compile-ubi8-juniper
