---

- template:
    name: build-centos
    streams:
      build-centos:
        vars:
          LINUX_DISTR: centos
          LINUX_DISTR_VER: 7
    jobs:
      prepare-sandbox-centos:
        # it creates worker
        job-name: build-prepare-sandbox
        stream: build-centos
        vars:
          DEVENV_TAG: frozen
      fetch-sources-centos:
        job-name: build-fetch-sources
        stream: build-centos
        depends-on:
          - prepare-sandbox-centos
      configure-centos:
        job-name: build-configure
        stream: build-centos
        depends-on:
          - fetch-sources-centos
      package-deployers-centos:
        job-name: build-package-deployers
        stream: build-centos
        depends-on:
          - configure-centos
      compile-centos:
        job-name: build-compile
        stream: build-centos
        depends-on:
          - package-deployers-centos
      package-centos:
        job-name: build-package
        stream: build-centos
        depends-on:
          - compile-centos
      freeze-centos:
        job-name: build-freeze
        stream: build-centos
        depends-on:
          - package-centos
        vars:
          PUBLISH_TYPE: frozen
      cleanup-centos:
        # it doesn't call devenv - it removes worker completly
        job-name: build-cleanup
        stream: build-centos
        type: post-hook
        depends-on:
          - freeze-centos

- template:
    name: build-rocky9
    streams:
      build-rocky9:
        vars:
          DEBUGINFO: "TRUE"
          LINUX_DISTR: rockylinux
          LINUX_DISTR_VER: 9
    jobs:
      prepare-sandbox-rocky9:
        # it creates worker
        job-name: build-prepare-sandbox
        stream: build-rocky9
        vars:
          DEVENV_TAG: frozen
      fetch-sources-rocky9:
        job-name: build-fetch-sources
        stream: build-rocky9
        depends-on:
          - prepare-sandbox-rocky9
      configure-rocky9:
        job-name: build-configure
        stream: build-rocky9
        depends-on:
          - fetch-sources-rocky9
      package-deployers-rocky9:
        job-name: build-package-deployers
        stream: build-rocky9
        depends-on:
          - configure-rocky9
      compile-rocky9:
        job-name: build-compile
        stream: build-rocky9
        depends-on:
          - package-deployers-rocky9
      package-rocky9:
        job-name: build-package
        stream: build-rocky9
        depends-on:
          - compile-rocky9
      freeze-rocky9:
        job-name: build-freeze
        stream: build-rocky9
        depends-on:
          - package-rocky9
        vars:
          PUBLISH_TYPE: frozen
      cleanup-rocky9:
        # it doesn't call devenv - it removes worker completly
        job-name: build-cleanup
        stream: build-rocky9
        type: post-hook
        depends-on:
          - freeze-rocky9

- template:
    name: build-r24.1-centos
    streams:
      build-r24.1-centos:
        voting: false
        vars:
          LINUX_DISTR: centos
          LINUX_DISTR_VER: 7
          GERRIT_BRANCH: "R24.1"
          TAG_SUFFIX: "-r24.1-centos"
    jobs:
      prepare-sandbox-r24.1-centos:
        # it creates worker
        job-name: build-prepare-sandbox
        stream: build-r24.1-centos
        vars:
          PUBLISH_TYPE: stable
      fetch-sources-r24.1-centos:
        job-name: build-fetch-sources
        stream: build-r24.1-centos
        depends-on:
          - prepare-sandbox-r24.1-centos
      configure-r24.1-centos:
        job-name: build-configure
        stream: build-r24.1-centos
        depends-on:
          - fetch-sources-r24.1-centos
      package-deployers-r24.1-centos:
        job-name: build-package-deployers
        stream: build-r24.1-centos
        depends-on:
          - configure-r24.1-centos
      compile-r24.1-centos:
        job-name: build-compile
        stream: build-r24.1-centos
        depends-on:
          - package-deployers-r24.1-centos
      package-r24.1-centos:
        job-name: build-package
        stream: build-r24.1-centos
        depends-on:
          - compile-r24.1-centos
      cleanup-r24.1-centos:
        # it doesn't call devenv - it removes worker completly
        job-name: build-cleanup
        stream: build-r24.1-centos
        type: post-hook
        depends-on:
          - package-r24.1-centos

- template:
    name: build-r25.1
    streams:
      build-r25.1:
        voting: false
        vars:
          GERRIT_BRANCH: "R25.1"
          TAG_SUFFIX: "-r25.1"
    jobs:
      prepare-sandbox-r25.1:
        # it creates worker
        job-name: build-prepare-sandbox
        stream: build-r25.1
        vars:
          PUBLISH_TYPE: stable
      fetch-sources-r25.1:
        job-name: build-fetch-sources
        stream: build-r25.1
        depends-on:
          - prepare-sandbox-r25.1
      configure-r25.1:
        job-name: build-configure
        stream: build-r25.1
        depends-on:
          - fetch-sources-r25.1
      package-deployers-r25.1:
        job-name: build-package-deployers
        stream: build-r25.1
        depends-on:
          - configure-r25.1
      compile-r25.1:
        job-name: build-compile
        stream: build-r25.1
        depends-on:
          - package-deployers-r25.1
      package-r25.1:
        job-name: build-package
        stream: build-r25.1
        depends-on:
          - compile-r25.1
      cleanup-r25.1:
        # it doesn't call devenv - it removes worker completly
        job-name: build-cleanup
        stream: build-r25.1
        type: post-hook
        depends-on:
          - package-r25.1
