---

- template:
    name: build-centos
    streams:
      build-centos:
        vars:
          LINUX_DISTR: centos
    jobs:
      prepare-sandbox-centos:
        # it creates worker
        job-name: build-prepare-sandbox
        stream: build-centos
        vars:
          DEVENV_TAG: frozen
      fetch-sources-centos:
        job-name: build-fetch-sources
        stream: build-centos
        depends-on:
          - prepare-sandbox-centos
      configure-centos:
        job-name: build-configure
        stream: build-centos
        depends-on:
          - fetch-sources-centos
      package-deployers-centos:
        job-name: build-package-deployers
        stream: build-centos
        depends-on:
          - configure-centos
      compile-centos:
        job-name: build-compile
        stream: build-centos
        depends-on:
          - package-deployers-centos
      package-centos:
        job-name: build-package
        stream: build-centos
        depends-on:
          - compile-centos
      freeze-centos:
        job-name: build-freeze
        stream: build-centos
        depends-on:
          - package-centos
        vars:
          PUBLISH_TYPE: frozen
      cleanup-centos:
        # it doesn't call devenv - it removes worker completly
        job-name: build-cleanup
        stream: build-centos
        type: post-hook
        depends-on:
          - freeze-centos

- template:
    name: build-ubi
    streams:
      build-ubi:
        vars:
          LINUX_DISTR: tf-mirrors.$SLAVE_REGION.$CI_DOMAIN:5005/ubi7/ubi
          LINUX_DISTR_VER: stable
          TAG_SUFFIX: "-ubi7"
          INSECURE_REGISTRIES: tf-mirrors.$SLAVE_REGION.$CI_DOMAIN:5005
    jobs:
      prepare-sandbox-ubi:
        # it creates worker
        job-name: build-prepare-sandbox
        stream: build-ubi
        vars:
          PUBLISH_TYPE: stable
      fetch-sources-ubi:
        job-name: build-fetch-sources
        stream: build-ubi
        depends-on:
          - prepare-sandbox-ubi
      configure-ubi:
        job-name: build-configure
        stream: build-ubi
        depends-on:
          - fetch-sources-ubi
      package-deployers-ubi:
        job-name: build-package-deployers
        stream: build-ubi
        depends-on:
          - configure-ubi
      compile-ubi:
        job-name: build-compile
        stream: build-ubi
        depends-on:
          - package-deployers-ubi
      package-ubi:
        job-name: build-package
        stream: build-ubi
        depends-on:
          - compile-ubi
      cleanup-ubi:
        # it doesn't call devenv - it removes worker completly
        job-name: build-cleanup
        stream: build-ubi
        type: post-hook
        depends-on:
          - package-ubi

- template:
    name: build-r1912-ubi
    streams:
      build-r1912-ubi:
        vars:
          LINUX_DISTR: tf-mirrors.$SLAVE_REGION.$CI_DOMAIN:5005/ubi7/ubi
          LINUX_DISTR_VER: stable
          TAG_SUFFIX: "-r1912-ubi7"
          INSECURE_REGISTRIES: tf-mirrors.$SLAVE_REGION.$CI_DOMAIN:5005
          GERRIT_BRANCH: "R1912"
    jobs:
        prepare-sandbox-r1912-ubi:
          # it creates worker
          job-name: build-prepare-sandbox
          stream: build-r1912-ubi
        fetch-sources-r1912-ubi:
          job-name: build-fetch-sources
          stream: build-r1912-ubi
          depends-on:
            - prepare-sandbox-r1912-ubi
        configure-r1912-ubi:
          job-name: build-configure
          stream: build-r1912-ubi
          depends-on:
            - fetch-sources-r1912-ubi
        package-deployers-r1912-ubi:
          job-name: build-package-deployers
          stream: build-r1912-ubi
          depends-on:
            - configure-r1912-ubi
        compile-r1912-ubi:
          job-name: build-compile
          stream: build-r1912-ubi
          depends-on:
            - package-deployers-r1912-ubi
        package-r1912-ubi:
          job-name: build-package
          stream: build-r1912-ubi
          depends-on:
            - compile-r1912-ubi
        cleanup-r1912-ubi:
          # it doesn't call devenv - it removes worker completly
          job-name: build-cleanup
          stream: build-r1912-ubi
          type: post-hook
          depends-on:
            - package-r1912-ubi

- template:
    name: build-r1912
    streams:
      build-r1912:
        vars:
          LINUX_DISTR: centos
          GERRIT_BRANCH: "R1912"
          TAG_SUFFIX: "-r1912"
    jobs:
      prepare-sandbox-r1912:
        # it creates worker
        job-name: build-prepare-sandbox
        stream: build-r1912
        vars:
          PUBLISH_TYPE: stable
      fetch-sources-r1912:
        job-name: build-fetch-sources
        stream: build-r1912
        depends-on:
          - prepare-sandbox-r1912
      configure-r1912:
        job-name: build-configure
        stream: build-r1912
        depends-on:
          - fetch-sources-r1912
      package-deployers-r1912:
        job-name: build-package-deployers
        stream: build-r1912
        depends-on:
          - configure-r1912
      compile-r1912:
        job-name: build-compile
        stream: build-r1912
        depends-on:
          - package-deployers-r1912
      package-r1912:
        job-name: build-package
        stream: build-r1912
        depends-on:
          - compile-r1912
      cleanup-r1912:
        # it doesn't call devenv - it removes worker completly
        job-name: build-cleanup
        stream: build-r1912
        type: post-hook
        depends-on:
          - package-r1912

- template:
    name: build-r2011-centos
    streams:
      build-r2011-centos:
        vars:
          LINUX_DISTR: centos
          GERRIT_BRANCH: "R2011"
          TAG_SUFFIX: "-r2011-centos"
    jobs:
      prepare-sandbox-r2011-centos:
        # it creates worker
        job-name: build-prepare-sandbox
        stream: build-r2011-centos
        vars:
          PUBLISH_TYPE: stable
      fetch-sources-r2011-centos:
        job-name: build-fetch-sources
        stream: build-r2011-centos
        depends-on:
          - prepare-sandbox-r2011-centos
      configure-r2011-centos:
        job-name: build-configure
        stream: build-r2011-centos
        depends-on:
          - fetch-sources-r2011-centos
      package-deployers-r2011-centos:
        job-name: build-package-deployers
        stream: build-r2011-centos
        depends-on:
          - configure-r2011-centos
      compile-r2011-centos:
        job-name: build-compile
        stream: build-r2011-centos
        depends-on:
          - package-deployers-r2011-centos
      package-r2011-centos:
        job-name: build-package
        stream: build-r2011-centos
        depends-on:
          - compile-r2011-centos
      cleanup-r2011-centos:
        # it doesn't call devenv - it removes worker completly
        job-name: build-cleanup
        stream: build-r2011-centos
        type: post-hook
        depends-on:
          - package-r2011-centos

- template:
    name: build-r2011-ubi
    streams:
      build-r2011-ubi:
        vars:
          LINUX_DISTR: tf-mirrors.$SLAVE_REGION.$CI_DOMAIN:5005/ubi7/ubi
          LINUX_DISTR_VER: stable
          TAG_SUFFIX: "-r2011-ubi7"
          INSECURE_REGISTRIES: tf-mirrors.$SLAVE_REGION.$CI_DOMAIN:5005
          GERRIT_BRANCH: "R2011"
    jobs:
        prepare-sandbox-r2011-ubi:
          # it creates worker
          job-name: build-prepare-sandbox
          stream: build-r2011-ubi
        fetch-sources-r2011-ubi:
          job-name: build-fetch-sources
          stream: build-r2011-ubi
          depends-on:
            - prepare-sandbox-r2011-ubi
        configure-r2011-ubi:
          job-name: build-configure
          stream: build-r2011-ubi
          depends-on:
            - fetch-sources-r2011-ubi
        package-deployers-r2011-ubi:
          job-name: build-package-deployers
          stream: build-r2011-ubi
          depends-on:
            - configure-r2011-ubi
        compile-r2011-ubi:
          job-name: build-compile
          stream: build-r2011-ubi
          depends-on:
            - package-deployers-r2011-ubi
        package-r2011-ubi:
          job-name: build-package
          stream: build-r2011-ubi
          depends-on:
            - compile-r2011-ubi
        cleanup-r2011-ubi:
          # it doesn't call devenv - it removes worker completly
          job-name: build-cleanup
          stream: build-r2011-ubi
          type: post-hook
          depends-on:
            - package-r2011-ubi

- template:
    name: build-ubi8
    streams:
      build-ubi8:
        vars:
          LINUX_DISTR: tf-mirrors.$SLAVE_REGION.$CI_DOMAIN:5005/ubi8/ubi
          LINUX_DISTR_VER: stable
          TAG_SUFFIX: "-ubi8"
          INSECURE_REGISTRIES: tf-mirrors.$SLAVE_REGION.$CI_DOMAIN:5005
          CONTRAIL_PARALLEL_BUILD: false
    jobs:
      prepare-sandbox-ubi8:
        # it creates worker
        job-name: build-prepare-sandbox
        stream: build-ubi8
        vars:
          PUBLISH_TYPE: stable
      fetch-sources-ubi8:
        job-name: build-fetch-sources
        stream: build-ubi8
        depends-on:
          - prepare-sandbox-ubi8
      configure-ubi8:
        job-name: build-configure
        stream: build-ubi8
        depends-on:
          - fetch-sources-ubi8
      package-deployers-ubi8:
        job-name: build-package-deployers
        stream: build-ubi8
        depends-on:
          - configure-ubi8
      compile-ubi8:
        job-name: build-compile
        stream: build-ubi8
        depends-on:
          - package-deployers-ubi8
      package-ubi8:
        job-name: build-package
        stream: build-ubi8
        depends-on:
          - compile-ubi8
      cleanup-ubi8:
        # it doesn't call devenv - it removes worker completly
        job-name: build-cleanup
        stream: build-ubi8
        type: post-hook
        depends-on:
          - package-ubi8