---

- template:
    name: ansible-os-not-implemented-targets
    streams:
      ansible-os-not-implemented-targets:
        vars:
          MONITORING_DEPLOY_TARGET: ISSU
          MONITORING_DEPLOYER: ansible
          MONITORING_ORCHESTRATOR: os

- template:
    name: ansible-k8s
    streams:
      ansible-k8s:
        voting: false
        vars:
          MONITORING_DEPLOY_TARGET: AIO
          MONITORING_DEPLOYER: ansible
          MONITORING_ORCHESTRATOR: k8s
    parents:
      - build-centos
    jobs:
      deploy-platform-ansible-k8s:
        stream: ansible-k8s
        depends-on:
          # temporary solution
          - compile-centos
      deploy-tf-ansible-k8s:
        stream: ansible-k8s
        depends-on:
          - package-centos
          - deploy-platform-ansible-k8s
      test-sanity-ansible-k8s:
        job-name: test-sanity
        stream: ansible-k8s
        depends-on:
          - deploy-tf-ansible-k8s
      test-deployment-ansible-k8s:
        job-name: test-deployment
        stream: ansible-k8s
        depends-on:
          - test-sanity-ansible-k8s
      collect-logs-and-cleanup-ansible-k8s:
        job-name: collect-logs-and-cleanup
        stream: ansible-k8s
        type: post-hook
        depends-on:
          - deploy-platform-ansible-k8s
          - deploy-tf-ansible-k8s
          - test-sanity-ansible-k8s
          - test-deployment-ansible-k8s

- template:
    name: ansible-k8s-ha
    streams:
      ansible-k8s-ha:
        vars:
          MONITORING_DEPLOY_TARGET: HA
          MONITORING_DEPLOYER: ansible
          MONITORING_ORCHESTRATOR: k8s
    parents:
      - build-centos
    jobs:
      deploy-platform-ansible-k8s-ha:
        job-name: deploy-platform-ansible-k8s
        stream: ansible-k8s-ha
        depends-on:
          # temporary solution
          - compile-centos
        vars:
          NODES: CONTROLLER_NODES:medium:3,AGENT_NODES:small:2
      deploy-tf-ansible-k8s-ha:
        job-name: deploy-tf-ansible-k8s
        stream: ansible-k8s-ha
        depends-on:
          - package-centos
          - deploy-platform-ansible-k8s-ha
      test-sanity-ansible-k8s-ha:
        job-name: test-sanity
        stream: ansible-k8s-ha
        depends-on:
          - deploy-tf-ansible-k8s-ha
      collect-logs-and-cleanup-ansible-k8s-ha:
        job-name: collect-logs-and-cleanup
        stream: ansible-k8s-ha
        type: post-hook
        depends-on:
          - deploy-platform-ansible-k8s-ha
          - deploy-tf-ansible-k8s-ha
          - test-sanity-ansible-k8s-ha

- template:
    name: ansible-os
    streams:
      ansible-os:
        vars:
          MONITORING_DEPLOY_TARGET: AIO
          MONITORING_DEPLOYER: ansible
          MONITORING_ORCHESTRATOR: os
          USE_DATAPLANE_NETWORK: true
    parents:
      - build-centos
    jobs:
      deploy-platform-ansible-os:
        stream: ansible-os
        depends-on:
          # temporary solution
          - package-centos
      deploy-tf-ansible-os:
        stream: ansible-os
        depends-on:
          - package-centos
          - deploy-platform-ansible-os
      test-sanity-ansible-os:
        job-name: test-sanity
        stream: ansible-os
        depends-on:
          - deploy-tf-ansible-os
      collect-logs-and-cleanup-ansible-os:
        job-name: collect-logs-and-cleanup
        stream: ansible-os
        type: post-hook
        depends-on:
          - deploy-platform-ansible-os
          - deploy-tf-ansible-os
          - test-sanity-ansible-os

- template:
    name: ansible-os-ha
    streams:
      ansible-os-ha:
        vars:
          MONITORING_DEPLOY_TARGET: HA
          MONITORING_DEPLOYER: ansible
          MONITORING_ORCHESTRATOR: os
          USE_DATAPLANE_NETWORK: true
    parents:
      - build-centos
    jobs:
      deploy-platform-ansible-os-ha:
        job-name: deploy-platform-ansible-os
        stream: ansible-os-ha
        depends-on:
          # temporary solution
          - package-centos
        vars:
          NODES: CONTROLLER_NODES:medium:3,AGENT_NODES:small:2
      deploy-tf-ansible-os-ha:
        job-name: deploy-tf-ansible-os
        stream: ansible-os-ha
        depends-on:
          - package-centos
          - deploy-platform-ansible-os-ha
      test-sanity-ansible-os-ha:
        job-name: test-sanity
        stream: ansible-os-ha
        depends-on:
          - deploy-tf-ansible-os-ha
      collect-logs-and-cleanup-ansible-os-ha:
        job-name: collect-logs-and-cleanup
        stream: ansible-os-ha
        type: post-hook
        depends-on:
          - deploy-platform-ansible-os-ha
          - deploy-tf-ansible-os-ha
          - test-sanity-ansible-os-ha

- template:
    name: ansible-os-ha-ziu
    streams:
      ansible-os-ha-ziu:
        vars:
          CONTAINER_REGISTRY: nexus.$SLAVE_REGION.$CI_DOMAIN:5002
          CONTRAIL_CONTAINER_TAG: nightly-r21.4-centos
          MONITORING_DEPLOY_TARGET: HA,ZIU
          MONITORING_DEPLOYER: ansible
          MONITORING_ORCHESTRATOR: os
          USE_DATAPLANE_NETWORK: true
    parents:
      - build-centos
    jobs:
      deploy-platform-ansible-os-ha-ziu:
        job-name: deploy-platform-ansible-os
        stream: ansible-os-ha-ziu
        vars:
          NODES: CONTROLLER_NODES:medium:3,AGENT_NODES:small:2
      deploy-tf-ansible-os-ha-ziu:
        job-name: deploy-tf-ansible-os
        stream: ansible-os-ha-ziu
        depends-on:
          - deploy-platform-ansible-os-ha-ziu
      test-deployment-ansible-os-ha-ziu:
        job-name: test-deployment
        stream: ansible-os-ha-ziu
        vars:
          DEPLOYMENT_TEST_TAGS: ziu
          TF_DEPLOYMENT_TEST_IMAGE: $CONTAINER_REGISTRY_ORIGINAL/tf-deployment-test:$CONTRAIL_CONTAINER_TAG_ORIGINAL
        depends-on:
          - package-centos
          - deploy-tf-ansible-os-ha-ziu
      test-sanity-ansible-os-ha-ziu:
        job-name: test-sanity
        stream: ansible-os-ha-ziu
        vars:
          TF_TEST_IMAGE: $CONTAINER_REGISTRY_ORIGINAL/contrail-test-test:$CONTRAIL_CONTAINER_TAG_ORIGINAL
        depends-on:
          - test-deployment-ansible-os-ha-ziu
      collect-logs-and-cleanup-ansible-os-ha-ziu:
        job-name: collect-logs-and-cleanup
        stream: ansible-os-ha-ziu
        type: post-hook
        depends-on:
          - deploy-platform-ansible-os-ha-ziu
          - deploy-tf-ansible-os-ha-ziu
          - test-deployment-ansible-os-ha-ziu
          - test-sanity-ansible-os-ha-ziu

- template:
    name: ansible-os-tempest
    streams:
      ansible-os-tempest:
        vars:
          USE_DATAPLANE_NETWORK: true
    parents:
      - build-centos
    jobs:
      deploy-platform-ansible-os-tempest:
        job-name: deploy-platform-ansible-os
        stream: ansible-os-tempest
        depends-on:
          # temporary solution
          - package-centos
      deploy-tf-ansible-os-tempest:
        job-name: deploy-tf-ansible-os
        stream: ansible-os-tempest
        depends-on:
          - package-centos
          - deploy-platform-ansible-os-tempest
      test-tempest-ansible-os-tempest:
        job-name: test-tempest
        stream: ansible-os-tempest
        depends-on:
          - deploy-tf-ansible-os-tempest
      collect-logs-and-cleanup-ansible-os-tempest:
        job-name: collect-logs-and-cleanup
        stream: ansible-os-tempest
        type: post-hook
        depends-on:
          - deploy-platform-ansible-os-tempest
          - deploy-tf-ansible-os-tempest
          - test-tempest-ansible-os-tempest

- template:
    name: ansible-full-sanity
    streams:
      ansible-full-sanity:
        vars:
          MONITORING_DEPLOY_TARGET: AIO
          MONITORING_DEPLOYER: ansible
          MONITORING_ORCHESTRATOR: os
          USE_DATAPLANE_NETWORK: true
          TF_TEST_TARGET: "full_sanity"
          ENVIRONMENT_OS: ubuntu20
    parents:
      - build-centos
    jobs:
      deploy-platform-ansible-full-sanity:
        job-name: deploy-platform-ansible-os
        stream: ansible-full-sanity
        depends-on:
          - compile-centos
      deploy-tf-ansible-full-sanity:
        job-name: deploy-tf-ansible-os
        stream: ansible-full-sanity
        depends-on:
          - package-centos
          - deploy-platform-ansible-full-sanity
      test-sanity-ansible-full-sanity:
        job-name: test-sanity
        stream: ansible-full-sanity
        depends-on:
          - deploy-tf-ansible-full-sanity
      collect-logs-and-cleanup-ansible-full-sanity:
        job-name: collect-logs-and-cleanup
        stream: ansible-full-sanity
        type: post-hook
        depends-on:
          - deploy-platform-ansible-full-sanity
          - deploy-tf-ansible-full-sanity
          - test-sanity-ansible-full-sanity

- template:
    name: ansible-os-vanilla
    streams:
      ansible-os-vanilla:
        vars:
          USE_DATAPLANE_NETWORK: true
          KOLLA_MODE: vanilla
    parents:
      - build-centos
    jobs:
      deploy-platform-ansible-os-vanilla:
        job-name: deploy-platform-ansible-os
        stream: ansible-os-vanilla
        depends-on:
          # temporary solution
          - package-centos
      deploy-tf-ansible-os-vanilla:
        job-name: deploy-tf-ansible-os
        stream: ansible-os-vanilla
        depends-on:
          - package-centos
          - deploy-platform-ansible-os-vanilla
      test-sanity-ansible-os-vanilla:
        job-name: test-sanity
        stream: ansible-os-vanilla
        depends-on:
          - deploy-tf-ansible-os-vanilla
      collect-logs-and-cleanup-ansible-os-vanilla:
        job-name: collect-logs-and-cleanup
        stream: ansible-os-vanilla
        type: post-hook
        depends-on:
          - deploy-platform-ansible-os-vanilla
          - deploy-tf-ansible-os-vanilla
          - test-sanity-ansible-os-vanilla
