---

- template:
    name: rhosp16-os-not-implemented-targets
    streams:
      rhosp16-os-not-implemented-targets:
        vars:
          MONITORING_DEPLOY_TARGET: PROD,ISSU,SR-IOV,DPDK,CCImport
          MONITORING_DEPLOYER: rhosp16
          MONITORING_ORCHESTRATOR: os

- template:
    name: rhosp16.2
    # to use latest deployer's code
    parents:
      - build-ubi8
    streams:
      rhosp16.2:
        vars:
          ENVIRONMENT_OS: rhel84
          TAG_SUFFIX: "-ubi8"
          DEPLOY_COMPACT_AIO: true
          ENABLE_RHEL_REGISTRATION: false
          OPENSTACK_CONTAINER_REGISTRY: "tf-mirrors.$SLAVE_REGION.$CI_DOMAIN:5005"
    jobs:
      deploy-platform-rhosp16.2:
        stream: rhosp16.2
        job-name: deploy-platform-rhosp16
      deploy-tf-rhosp16.2:
        stream: rhosp16.2
        job-name: deploy-tf-rhosp16
        depends-on:
          - package-ubi8
          - deploy-platform-rhosp16.2
      test-sanity-rhosp16.2:
        job-name: test-sanity
        stream: rhosp16.2
        depends-on:
          - deploy-tf-rhosp16.2
      collect-logs-and-cleanup-rhosp16.2:
        job-name: collect-logs-and-cleanup
        stream: rhosp16.2
        type: post-hook
        depends-on:
          - deploy-platform-rhosp16.2
          - deploy-tf-rhosp16.2
          - test-sanity-rhosp16.2

- template:
    name: rhosp16.2-ha
    # to use latest deployer's code
    parents:
      - build-ubi8
    streams:
      rhosp16.2-ha:
        vars:
          ENVIRONMENT_OS: rhel84
          TAG_SUFFIX: "-ubi8"
          SSL_ENABLE: true
          DEPLOY_COMPACT_AIO: true
          ENABLE_RHEL_REGISTRATION: false
          OPENSTACK_CONTAINER_REGISTRY: "tf-mirrors.$SLAVE_REGION.$CI_DOMAIN:5005"
          NODES: 'OPENSTACK_CONTROLLER_NODES:medium:1,CONTROLLER_NODES:medium:3,AGENT_NODES:small:1'
    jobs:
      deploy-platform-rhosp16.2-ha:
        stream: rhosp16.2-ha
        job-name: deploy-platform-rhosp16
      deploy-tf-rhosp16.2-ha:
        stream: rhosp16.2-ha
        job-name: deploy-tf-rhosp16
        depends-on:
          - package-ubi8
          - deploy-platform-rhosp16.2-ha
      test-sanity-rhosp16.2-ha:
        job-name: test-sanity
        stream: rhosp16.2-ha
        depends-on:
          - deploy-tf-rhosp16.2-ha
      collect-logs-and-cleanup-rhosp16.2-ha:
        job-name: collect-logs-and-cleanup
        stream: rhosp16.2-ha
        type: post-hook
        depends-on:
          - deploy-platform-rhosp16.2-ha
          - deploy-tf-rhosp16.2-ha
          - test-sanity-rhosp16.2-ha

- template:
    name: rhosp16.1
    parents:
      - build-ubi
    streams:
      rhosp16.1:
        vars:
          ENVIRONMENT_OS: rhel82
          TAG_SUFFIX: "-ubi7"
          SSL_ENABLE: true
          ENABLE_RHEL_REGISTRATION: false
          NODES: 'OPENSTACK_CONTROLLER_NODES:medium:1,CONTROLLER_NODES:medium:3,AGENT_NODES:small:1'
          OPENSTACK_CONTAINER_REGISTRY: "tf-mirrors.$SLAVE_REGION.$CI_DOMAIN:5005"
          MONITORING_DEPLOY_TARGET: HA
          MONITORING_DEPLOYER: rhosp16
          MONITORING_ORCHESTRATOR: os
    jobs:
      deploy-platform-rhosp16.1:
        job-name: deploy-platform-rhosp16
        stream: rhosp16.1
      deploy-tf-rhosp16.1:
        job-name: deploy-tf-rhosp16
        stream: rhosp16.1
        depends-on:
          - package-ubi
          - deploy-platform-rhosp16.1
      test-sanity-rhosp16.1:
        job-name: test-sanity
        stream: rhosp16.1
        depends-on:
          - deploy-tf-rhosp16.1
      collect-logs-and-cleanup-rhosp16.1:
        job-name: collect-logs-and-cleanup
        stream: rhosp16.1
        type: post-hook
        depends-on:
          - deploy-platform-rhosp16.1
          - deploy-tf-rhosp16.1
          - test-sanity-rhosp16.1

- template:
    name: rhosp16.1-bmc
    parents:
      - build-ubi-deployers
    streams:
      rhosp16.1-bmc:
        lock: openlab1
        vars:
          JUMPHOST: openlab1
          ENVIRONMENT_OS: rhel82
          TAG_SUFFIX: "-ubi8"
          SSL_ENABLE: true
          ENABLE_RHEL_REGISTRATION: false
          ENABLE_NETWORK_ISOLATION: true
          OPENSTACK_CONTAINER_REGISTRY: "mirrors:5005"
          CONTRAIL_CONTAINER_TAG: 'nightly'
          CONTAINER_REGISTRY: "nexus.$SLAVE_REGION.$CI_DOMAIN:5102"
          MONITORING_DEPLOY_TARGET: PROD,SR-IOV,DPDK
          MONITORING_DEPLOYER: rhosp16
          MONITORING_ORCHESTRATOR: os
    jobs:
      deploy-platform-rhosp16.1-bmc:
        job-name: deploy-platform-rhosp16
        stream: rhosp16.1-bmc
      deploy-tf-rhosp16.1-bmc:
        job-name: deploy-tf-rhosp16
        stream: rhosp16.1-bmc
        timeout: 240
        depends-on:
          - package-deployers-ubi-deployers
          - deploy-platform-rhosp16.1-bmc
      test-sanity-rhosp16.1-bmc:
        job-name: test-sanity
        stream: rhosp16.1-bmc
        depends-on:
          - deploy-tf-rhosp16.1-bmc
      collect-logs-and-cleanup-rhosp16.1-bmc:
        job-name: collect-logs-and-cleanup
        stream: rhosp16.1-bmc
        type: post-hook
        depends-on:
          - deploy-platform-rhosp16.1-bmc
          - deploy-tf-rhosp16.1-bmc
          - test-sanity-rhosp16.1-bmc

- template:
    name: rhosp16.2-bmc
    parents:
      - build-ubi8
    streams:
      rhosp16.2-bmc:
        lock: openlab1
        vars:
          JUMPHOST: openlab1
          ENVIRONMENT_OS: rhel84
          TAG_SUFFIX: "-ubi8"
          SSL_ENABLE: true
          ENABLE_RHEL_REGISTRATION: false
          ENABLE_NETWORK_ISOLATION: true
          OPENSTACK_CONTAINER_REGISTRY: "mirrors:5005"
          MONITORING_DEPLOY_TARGET: PROD,SR-IOV,DPDK
          MONITORING_DEPLOYER: rhosp16
          MONITORING_ORCHESTRATOR: os
    jobs:
      deploy-platform-rhosp16.2-bmc:
        job-name: deploy-platform-rhosp16
        stream: rhosp16.2-bmc
      deploy-tf-rhosp16.2-bmc:
        job-name: deploy-tf-rhosp16
        stream: rhosp16.2-bmc
        timeout: 240
        depends-on:
          - package-ubi8
          - deploy-platform-rhosp16.2-bmc
      test-sanity-rhosp16.2-bmc:
        job-name: test-sanity
        stream: rhosp16.2-bmc
        depends-on:
          - deploy-tf-rhosp16.2-bmc
      collect-logs-and-cleanup-rhosp16.2-bmc:
        job-name: collect-logs-and-cleanup
        stream: rhosp16.2-bmc
        type: post-hook
        depends-on:
          - deploy-platform-rhosp16.2-bmc
          - deploy-tf-rhosp16.2-bmc
          - test-sanity-rhosp16.2-bmc

- template:
    name: rhosp16.2-slave04
    parents:
      - build-ubi-deployers
    streams:
      rhosp16.2-slave04:
        lock: openlab4
        vars:
          DEBUG: true
          JUMPHOST: openlab4
          ENVIRONMENT_OS: rhel84
          TAG_SUFFIX: "-ubi8"
          ENABLE_RHEL_REGISTRATION: true
          CONTRAIL_CONTAINER_TAG: 'nightly'
          CONTAINER_REGISTRY: 'nexus.$SLAVE_REGION.$CI_DOMAIN:5102'
          ENABLE_NETWORK_ISOLATION: false
          HUGEPAGES_ENABLED: false
          SSL_ENABLE: true
          NODES: 'OPENSTACK_CONTROLLER_NODES:medium:1,CONTROLLER_NODES:medium:1,AGENT_NODES:small:1'
    jobs:
      deploy-platform-rhosp16.2-slave04:
        job-name: deploy-platform-rhosp16
        stream: rhosp16.2-slave04
      deploy-tf-rhosp16.2-slave04:
        job-name: deploy-tf-rhosp16
        stream: rhosp16.2-slave04
        timeout: 240
        depends-on:
          - package-deployers-ubi-deployers
          - deploy-platform-rhosp16.2-slave04
      test-sanity-rhosp16.2-slave04:
        job-name: test-sanity
        stream: rhosp16.2-slave04
        depends-on:
          - deploy-tf-rhosp16.2-slave04
      collect-logs-and-cleanup-rhosp16.2-slave04:
        job-name: collect-logs-and-cleanup
        stream: rhosp16.2-slave04
        type: post-hook
        depends-on:
          - deploy-platform-rhosp16.2-slave04
          - deploy-tf-rhosp16.2-slave04
          - test-sanity-rhosp16.2-slave04
