---

- template:
    name: prepare-sources
    streams:
      prepare-sources:
        vars:
          LINUX_DISTR: centos
    jobs:
      prepare-sandbox-sources:
        # it creates worker
        job-name: build-prepare-sandbox
        stream: prepare-sources
        vars:
          PUBLISH_TYPE: stable
          VM_TYPE: small
      fetch-sources:
        job-name: build-fetch-sources
        stream: prepare-sources
        depends-on:
          - prepare-sandbox-sources
        vars:
          PUBLISH_TYPE: build
      cleanup-worker-sources:
        # it doesn't call devenv - it removes worker completly
        job-name: build-cleanup
        stream: prepare-sources
        type: stream-post-hook
        depends-on:
          - fetch-sources

- template:
    name: test-unit
    parents:
      - prepare-sources
    jobs:
      test-unit-agent:
        stream: test-unit
        depends-on:
          - fetch-sources:
              inherit-keys:
                - DEVENV_TAG
                - UNITTEST_TARGETS
      test-unit-opserver:
        stream: test-unit
        depends-on:
          - fetch-sources:
              inherit-keys:
                - DEVENV_TAG
                - UNITTEST_TARGETS
      test-unit-bgp:
        stream: test-unit
        depends-on:
          - fetch-sources:
              inherit-keys:
                - DEVENV_TAG
                - UNITTEST_TARGETS
      test-unit-group-one:
        stream: test-unit
        depends-on:
          - fetch-sources:
              inherit-keys:
                - DEVENV_TAG
                - UNITTEST_TARGETS
      test-unit-ungrouped:
        stream: test-unit
        depends-on:
          - fetch-sources:
              inherit-keys:
                - DEVENV_TAG
                - UNITTEST_TARGETS

# TODO: think about moving this job into k8s cluster somehow
- template:
    name: test-unit-ui
    parents:
      - prepare-sources
    jobs:
      test-unit-ui:
        depends-on:
          - fetch-sources:
              inherit-keys:
                - DEVENV_TAG

- template:
    name: test-tox-pep8
    parents:
      - prepare-sources
    jobs:
      test-unit-tox:
        depends-on:
          - fetch-sources:
              inherit-keys:
                - DEVENV_TAG
        vars:
          TARGET_SET: pep8
