---

- template:
    name: operator
    streams:
      operator:
        vars:
          # operator is always ssl
          SSL_ENABLE: true
          MONITORING_DEPLOY_TARGET: AIO
          MONITORING_DEPLOYER: operator
          MONITORING_ORCHESTRATOR: k8s
    parents:
      - build-centos
    jobs:
      deploy-platform-operator:
        stream: operator
      deploy-tf-operator:
        stream: operator
        depends-on:
          - package-centos
          - deploy-platform-operator
      test-sanity-operator:
        job-name: test-sanity
        stream: operator
        depends-on:
          - deploy-tf-operator
      collect-logs-and-cleanup-operator:
        job-name: collect-logs-and-cleanup
        stream: operator
        type: post-hook
        depends-on:
          - deploy-platform-operator
          - deploy-tf-operator
          - test-sanity-operator

- template:
    name: operator-ha
    streams:
      operator-ha:
        voting: false
        vars:
          # operator is always ssl
          SSL_ENABLE: true
          MONITORING_DEPLOY_TARGET: HA
          MONITORING_DEPLOYER: operator
          MONITORING_ORCHESTRATOR: k8s
    parents:
      - build-centos
    jobs:
      deploy-platform-operator-ha:
        job-name: deploy-platform-operator
        stream: operator-ha
        vars:
          NODES: CONTROLLER_NODES:medium:3,AGENT_NODES:small:2
      deploy-tf-operator-ha:
        job-name: deploy-tf-operator
        stream: operator-ha
        depends-on:
          - package-centos
          - deploy-platform-operator-ha
      test-sanity-operator-ha:
        job-name: test-sanity
        stream: operator-ha
        depends-on:
          - deploy-tf-operator-ha
      collect-logs-and-cleanup-operator-ha:
        job-name: collect-logs-and-cleanup
        stream: operator-ha
        type: post-hook
        depends-on:
          - deploy-platform-operator-ha
          - deploy-tf-operator-ha
          - test-sanity-operator-ha
