---

- template:
    name: operator
    streams:
      operator:
        vars:
          # operator is always ssl
          SSL_ENABLE: true
          MONITORING_DEPLOY_TARGET: AIO
          MONITORING_DEPLOYER: operator
          MONITORING_ORCHESTRATOR: k8s
          HUGE_PAGES_2MB: 512
    parents:
      - build-centos
    jobs:
      deploy-platform-operator:
        stream: operator
      deploy-tf-operator:
        stream: operator
        depends-on:
          - package-centos
          - deploy-platform-operator
      test-sanity-operator:
        job-name: test-sanity
        stream: operator
        depends-on:
          - deploy-tf-operator
      test-deployment-operator:
        job-name: test-deployment
        stream: operator
        depends-on:
          - test-sanity-operator
      collect-logs-and-cleanup-operator:
        job-name: collect-logs-and-cleanup
        stream: operator
        type: post-hook
        depends-on:
          - deploy-platform-operator
          - deploy-tf-operator
          - test-sanity-operator
          - test-deployment-operator

# This is only for nightly
- template:
    name: operator-2011
    streams:
      operator-2011:
        vars:
          # operator is always ssl
          SSL_ENABLE: true
          MONITORING_DEPLOY_TARGET: ILTS
          MONITORING_DEPLOYER: operator
          MONITORING_ORCHESTRATOR: k8s
          HUGE_PAGES_2MB: 512
          GERRIT_BRANCH: "R2011"
    parents:
      - build-r2011-centos
    jobs:
      deploy-platform-operator-2011:
        job-name: deploy-platform-operator
        stream: operator-2011
      deploy-tf-operator-2011:
        job-name: deploy-tf-operator
        stream: operator-2011
        depends-on:
          - package-r2011-centos
          - deploy-platform-operator-2011
      test-sanity-operator-2011:
        job-name: test-sanity
        stream: operator-2011
        depends-on:
          - deploy-tf-operator-2011
      test-deployment-operator-2011:
        job-name: test-deployment
        stream: operator-2011
        depends-on:
          - test-sanity-operator-2011
      collect-logs-and-cleanup-operator-2011:
        job-name: collect-logs-and-cleanup
        stream: operator-2011
        type: post-hook
        depends-on:
          - deploy-platform-operator-2011
          - deploy-tf-operator-2011
          - test-sanity-operator-2011
          - test-deployment-operator-2011

- template:
    name: operator-ha
    streams:
      operator-ha:
        voting: false
        vars:
          CONFIG_API_WORKER_COUNT: 3
          # operator is always ssl
          SSL_ENABLE: true
          MONITORING_DEPLOY_TARGET: HA
          MONITORING_DEPLOYER: operator
          MONITORING_ORCHESTRATOR: k8s
          HUGE_PAGES_2MB: 512
    parents:
      - build-centos
    jobs:
      deploy-platform-operator-ha:
        job-name: deploy-platform-operator
        stream: operator-ha
        vars:
          NODES: CONTROLLER_NODES:medium:3,AGENT_NODES:small:2
      deploy-tf-operator-ha:
        job-name: deploy-tf-operator
        stream: operator-ha
        depends-on:
          - package-centos
          - deploy-platform-operator-ha
      test-sanity-operator-ha:
        job-name: test-sanity
        stream: operator-ha
        depends-on:
          - deploy-tf-operator-ha
      test-deployment-operator-ha:
        job-name: test-deployment
        stream: operator-ha
        depends-on:
          - test-sanity-operator-ha
      collect-logs-and-cleanup-operator-ha:
        job-name: collect-logs-and-cleanup
        stream: operator-ha
        type: post-hook
        depends-on:
          - deploy-platform-operator-ha
          - deploy-tf-operator-ha
          - test-sanity-operator-ha
          - test-deployment-operator-ha
