---

- template:
    name: cleanup
    post-jobs:
      cleanup-pipeline-workers:

- template:
    name: build-centos
    streams:
      build-centos:
    jobs:
      prepare-sandbox-centos:
        job-name: build
        stream: build-centos
        vars:
          # stage 'none' creates worker
          STAGE: none
          PUBLISH: stable
      fetch-sources-centos:
        job-name: build
        stream: build-centos
        depends-on:
          - prepare-sandbox-centos
        vars:
          STAGE: ""
          PUBLISH: build
      package-deployers-centos:
        job-name: build
        stream: build-centos
        depends-on:
          - fetch-sources-centos
        vars:
          STAGE: package
          TARGET: src-containers-only
      compile-centos:
        job-name: build
        stream: build-centos
        depends-on:
          - package-deployers-centos
        vars:
          STAGE: compile
      package-containers-centos:
        job-name: build
        stream: build-centos
        depends-on:
          - compile-centos
        vars:
          STAGE: package
          TARGET: containers
      package-test-containers-centos:
        job-name: build
        stream: build-centos
        depends-on:
          - package-containers-centos
        vars:
          STAGE: package
          TARGET: test-containers
      freeze-centos:
        job-name: build
        stream: build-centos
        depends-on:
          - package-test-containers-centos
        vars:
          PIPLINE_FILTER: "gate,nightly"
          STAGE: freeze
          PUBLISH: frozen
      cleanup-build-centos:
        job-name: build
        stream: build-centos
        type: stream-post-hook
        depends-on:
          - freeze-centos
        vars:
          # it doesn't call devenv - it removes worker completly
          STAGE: cleanup

- template:
    name: build-rhel
    streams:
      build-rhel:
        vars:
          ENVIRONMENT_OS: rhel7
          TAG_SUFFIX: -rhel7
    jobs:
      prepare-sandbox-rhel:
        job-name: build
        stream: build-rhel
        vars:
          # stage 'none' creates worker
          STAGE: none
          PUBLISH: stable
      fetch-sources-rhel:
        job-name: build
        stream: build-rhel
        depends-on:
          - prepare-sandbox-rhel
        vars:
          STAGE: ""
          PUBLISH: build
      package-deployers-rhel:
        job-name: build
        stream: build-rhel
        depends-on:
          - fetch-sources-rhel
        vars:
          STAGE: package
          TARGET: src-containers-only
      compile-rhel:
        job-name: build
        stream: build-rhel
        depends-on:
          - package-deployers-rhel
        vars:
          STAGE: compile
      package-containers-rhel:
        job-name: build
        stream: build-rhel
        depends-on:
          - compile-rhel
        vars:
          STAGE: package
          TARGET: containers
      package-test-containers-rhel:
        job-name: build
        stream: build-rhel
        depends-on:
          - package-containers-rhel
        vars:
          STAGE: package
          TARGET: test-containers
      freeze-rhel:
        job-name: build
        stream: build-rhel
        depends-on:
          - package-test-containers-rhel
        vars:
          PIPLINE_FILTER: "gate,nightly"
          STAGE: freeze
          PUBLISH: frozen
      cleanup-build-rhel:
        job-name: build
        stream: build-rhel
        type: stream-post-hook
        depends-on:
          - freeze-rhel
        vars:
          # it doesn't call devenv - it removes worker completly
          STAGE: cleanup

- template:
    name: test-unit
    parents:
      - build-centos
    streams:
      test-unit:
    jobs:
      test-unit-compile:
        job-name: test-unit
        stream: test-unit
        depends-on:
          - fetch-sources-centos
        vars:
          STAGE: compile
          TARGET: test
          DEVENV_PUSH_TAG: "-compiled"
      test-unit-agent:
        job-name: test-unit
        stream: test-unit
        depends-on:
          - test-unit-compile
        vars:
          TARGET_SET: agent
      test-unit-opserver:
        job-name: test-unit
        stream: test-unit
        depends-on:
          - test-unit-compile
        vars:
          TARGET_SET: opserver
      test-unit-bgp:
        job-name: test-unit
        stream: test-unit
        depends-on:
          - test-unit-compile
        vars:
          TARGET_SET: bgp
      test-unit-group-one:
        job-name: test-unit
        stream: test-unit
        depends-on:
          - test-unit-compile
        vars:
          TARGET_SET: group_one
      test-unit:
        job-name: test-unit
        stream: test-unit
        depends-on:
          - test-unit-compile
        vars:
          TARGET_SET: UNGROUPED

- template:
    name: test-unit-ui
    parents:
      - build-centos
    jobs:
      test-unit-ui:
        job-name: test-unit
        depends-on:
          - fetch-sources-centos
        vars:
          TARGET: ui

- template:
    name: k8s-manifests
    parents:
      - build-centos
    streams:
      k8s-manifests:
        voting: false
    jobs:
      deploy-platform-k8s-manifests:
        stream: k8s-manifests
      deploy-tf-k8s-manifests:
        stream: k8s-manifests
        depends-on:
          - package-containers-centos
          - deploy-platform-k8s-manifests
      test-sanity-k8s-manifests:
        job-name: test-sanity
        stream: k8s-manifests
        depends-on:
          - package-test-containers-centos
          - deploy-tf-k8s-manifests
      test-smoke-k8s-manifests:
        job-name: test-smoke
        stream: k8s-manifests
        depends-on:
          - deploy-tf-k8s-manifests
      collect-logs-and-cleanup-k8s-manifests:
        # 1. run after all stream jobs if any of stream jobs was run
        # 2. shouldn't be included into report
        # 3. should not dictate how to wait - wait_for_deps should exit on first fail and do not wait for all
        job-name: collect-logs-and-cleanup
        stream: k8s-manifests
        type: stream-post-hook
        depends-on:
          - deploy-platform-k8s-manifests
          - deploy-tf-k8s-manifests
          - test-sanity-k8s-manifests
          - test-smoke-k8s-manifests

- template:
    name: ansible-k8s
    parents:
      - build-centos
    streams:
      ansible-k8s:
    jobs:
      deploy-platform-ansible-k8s:
        stream: ansible-k8s
        depends-on:
          # temporary solution
          - compile-centos
      deploy-tf-ansible-k8s:
        stream: ansible-k8s
        depends-on:
          - package-containers-centos
          - deploy-platform-ansible-k8s
      test-sanity-ansible-k8s:
        job-name: test-sanity
        stream: ansible-k8s
        depends-on:
          - package-test-containers-centos
          - deploy-tf-ansible-k8s
      collect-logs-and-cleanup-ansible-k8s:
        job-name: collect-logs-and-cleanup
        stream: ansible-k8s
        type: stream-post-hook
        depends-on:
          - deploy-platform-ansible-k8s
          - deploy-tf-ansible-k8s
          - test-sanity-ansible-k8s

- template:
    name: ansible-os
    parents:
      - build-centos
    streams:
      ansible-os:
    jobs:
      deploy-platform-ansible-os:
        stream: ansible-os
        depends-on:
          # temporary solution
          - compile-centos
      deploy-tf-ansible-os:
        stream: ansible-os
        depends-on:
          - package-containers-centos
          - deploy-platform-ansible-os
      test-sanity-ansible-os:
        job-name: test-sanity
        stream: ansible-os
        depends-on:
          - package-test-containers-centos
          - deploy-tf-ansible-os
      collect-logs-and-cleanup-ansible-os:
        job-name: collect-logs-and-cleanup
        stream: ansible-os
        type: stream-post-hook
        depends-on:
          - deploy-platform-ansible-os
          - deploy-tf-ansible-os
          - test-sanity-ansible-os

- template:
    name: helm-k8s
    parents:
      - build-centos
    streams:
      helm-k8s:
    jobs:
      deploy-platform-helm-k8s:
        stream: helm-k8s
      deploy-tf-helm-k8s:
        stream: helm-k8s
        depends-on:
          - package-containers-centos
          - deploy-platform-helm-k8s
      test-sanity-helm-k8s:
        job-name: test-sanity
        stream: helm-k8s
        depends-on:
          - package-test-containers-centos
          - deploy-tf-helm-k8s
      collect-logs-and-cleanup-helm-k8s:
        job-name: collect-logs-and-cleanup
        stream: helm-k8s
        type: stream-post-hook
        depends-on:
          - deploy-platform-helm-k8s
          - deploy-tf-helm-k8s
          - test-sanity-helm-k8s

- template:
    name: helm-os
    parents:
      - build-centos
    streams:
      helm-os:
    jobs:
      deploy-platform-helm-os:
        stream: helm-os
      deploy-tf-helm-os:
        stream: helm-os
        depends-on:
          - package-containers-centos
          - deploy-platform-helm-os
      test-sanity-helm-os:
        job-name: test-sanity
        stream: helm-os
        depends-on:
          - package-test-containers-centos
          - deploy-tf-helm-os
      collect-logs-and-cleanup-helm-os:
        job-name: collect-logs-and-cleanup
        stream: helm-os
        type: stream-post-hook
        depends-on:
          - deploy-platform-helm-os
          - deploy-tf-helm-os
          - test-sanity-helm-os

- template:
    name: juju-k8s
    parents:
      - build-centos
    streams:
      juju-k8s:
    jobs:
      deploy-platform-juju-k8s:
        stream: juju-k8s
      deploy-tf-juju-k8s:
        stream: juju-k8s
        depends-on:
          - package-containers-centos
          - deploy-platform-juju-k8s
      test-sanity-juju-k8s:
        job-name: test-sanity
        stream: juju-k8s
        depends-on:
          - package-test-containers-centos
          - deploy-tf-juju-k8s
      collect-logs-and-cleanup-juju-k8s:
        job-name: collect-logs-and-cleanup
        stream: juju-k8s
        type: stream-post-hook
        depends-on:
          - deploy-platform-juju-k8s
          - deploy-tf-juju-k8s
          - test-sanity-juju-k8s

- template:
    name: juju-os
    parents:
      - build-centos
    streams:
      juju-os:
    jobs:
      deploy-platform-juju-os:
        stream: juju-os
      deploy-tf-juju-os:
        stream: juju-os
        depends-on:
          - package-containers-centos
          - deploy-platform-juju-os
      test-sanity-juju-os:
        job-name: test-sanity
        stream: juju-os
        depends-on:
          - package-test-containers-centos
          - deploy-tf-juju-os
      collect-logs-and-cleanup-juju-os:
        job-name: collect-logs-and-cleanup
        stream: juju-os
        type: stream-post-hook
        depends-on:
          - deploy-platform-juju-os
          - deploy-tf-juju-os
          - test-sanity-juju-os

- template:
    name: juju-maas-os
    parents:
      - build-centos
    streams:
      juju-maas-os:
    jobs:
      deploy-platform-juju-maas-os:
        stream: juju-maas-os
        vars:
          CLOUD: maas
      deploy-tf-juju-maas-os:
        stream: juju-maas-os
        depends-on:
          - package-containers-centos
          - deploy-platform-juju-maas-os
        vars:
          CLOUD: maas
      test-sanity-juju-maas-os:
        job-name: test-sanity
        stream: juju-maas-os
        depends-on:
          - package-test-containers-centos
          - deploy-tf-juju-maas-os
      collect-logs-and-cleanup-juju-maas-os:
        job-name: collect-logs-and-cleanup
        stream: juju-maas-os
        type: stream-post-hook
        depends-on:
          - deploy-platform-juju-maas-os
          - deploy-tf-juju-maas-os
          - test-sanity-juju-maas-os

- template:
    name: rhosp
    parents:
      - build-rhel
    streams:
      rhosp:
    jobs:
      deploy-platform-rhosp:
        stream: rhosp
        vars:
          ENVIRONMENT_OS: rhel7
          TAG_SUFFIX: -rhel7
      deploy-tf-rhosp:
        stream: rhosp
        depends-on:
          - package-containers-rhel
          - deploy-platform-rhosp
        vars:
          TAG_SUFFIX: -rhel7
      test-sanity-rhosp:
        job-name: test-sanity
        stream: rhosp
        depends-on:
          - package-test-containers-rhel
          - deploy-tf-rhosp
        vars:
          TAG_SUFFIX: -rhel7
      collect-logs-and-cleanup-rhosp:
        job-name: collect-logs-and-cleanup
        stream: rhosp
        type: stream-post-hook
        depends-on:
          - deploy-platform-rhosp
          - deploy-tf-rhosp
          - test-sanity-rhosp
        vars:
          TAG_SUFFIX: -rhel7

- template:
    name: openshift
    parents:
      - build-rhel
    streams:
      openshift:
    jobs:
      deploy-platform-openshift:
        stream: openshift
        depends-on:
          - build-rhel
        vars:
          ENVIRONMENT_OS: rhel7
          TAG_SUFFIX: -rhel7
          RHEL_OPENSHIFT_REGISTRY: rhel-mirrors.tf-jenkins.progmaticlab.com:5000
      deploy-tf-openshift:
        stream: openshift
        depends-on:
          - package-containers-rhel
          - deploy-platform-openshift
        vars:
          TAG_SUFFIX: -rhel7
          RHEL_OPENSHIFT_REGISTRY: rhel-mirrors.tf-jenkins.progmaticlab.com:5000
      test-sanity-openshift:
        job-name: test-sanity
        stream: openshift
        depends-on:
          - package-test-containers-rhel
          - deploy-tf-openshift
        vars:
          TAG_SUFFIX: -rhel7
      collect-logs-and-cleanup-openshift:
        job-name: collect-logs-and-cleanup
        stream: openshift
        type: stream-post-hook
        depends-on:
          - deploy-platform-openshift
          - deploy-tf-openshift
          - test-sanity-openshift
        vars:
          TAG_SUFFIX: -rhel7
