---

# this is sandbox for old style UT - scons and webui
# this template prepares sandbox, run fetch & configure and then pushes it to registry
# next jobs will create new workers, pull prepared sandbox and run tests
- template:
    name: prepare-ut-sandbox
    streams:
      prepare-ut-sandbox:
        vars:
          LINUX_DISTR: centos
    jobs:
      prepare-sandbox-ut-sandbox:
        # it creates worker
        job-name: build-prepare-sandbox
        stream: prepare-ut-sandbox
        vars:
          PUBLISH_TYPE: stable
          VM_TYPE: small
      # tox tests require just sources
      fetch-sources-ut-sandbox:
        job-name: build-fetch-sources
        stream: prepare-ut-sandbox
        depends-on:
          - prepare-sandbox-ut-sandbox
      # controller's UT requires a lot of stuff that is installed during configure stage
      # UI UT requires build deps from contrail-web-core/contrail-web-controller
      configure-ut-sandbox:
        job-name: build-configure
        stream: prepare-ut-sandbox
        depends-on:
          - fetch-sources-ut-sandbox
        vars:
          PUBLISH_TYPE: build
      cleanup-worker-ut-sandbox:
        # it doesn't call devenv - it removes worker completly
        job-name: build-cleanup
        stream: prepare-ut-sandbox
        type: post-hook
        depends-on:
          - configure-ut-sandbox

- template:
    name: test-unit
    parents:
      - prepare-ut-sandbox
    streams:
      test-unit:
        vars:
          LINUX_DISTR: centos
    jobs:
      test-unit-agent:
        stream: test-unit
        depends-on:
          - configure-ut-sandbox:
              inherit-keys:
                - DEVENV_TAG
                - UNITTEST_TARGETS
      test-unit-opserver:
        stream: test-unit
        depends-on:
          - configure-ut-sandbox:
              inherit-keys:
                - DEVENV_TAG
                - UNITTEST_TARGETS
      test-unit-bgp:
        stream: test-unit
        depends-on:
          - configure-ut-sandbox:
              inherit-keys:
                - DEVENV_TAG
                - UNITTEST_TARGETS
      test-unit-group-one:
        stream: test-unit
        depends-on:
          - configure-ut-sandbox:
              inherit-keys:
                - DEVENV_TAG
                - UNITTEST_TARGETS
      test-unit-group-two:
        stream: test-unit
        depends-on:
          - configure-ut-sandbox:
              inherit-keys:
                - DEVENV_TAG
                - UNITTEST_TARGETS
      test-unit-ungrouped:
        stream: test-unit
        depends-on:
          - configure-ut-sandbox:
              inherit-keys:
                - DEVENV_TAG
                - UNITTEST_TARGETS

# TODO: think about moving these below jobs into k8s cluster somehow
- template:
    name: test-unit-ui
    parents:
      - prepare-ut-sandbox
    streams:
      test-unit-ui:
        vars:
          LINUX_DISTR: centos
    jobs:
      test-unit-ui:
        depends-on:
          - configure-ut-sandbox:
              inherit-keys:
                - DEVENV_TAG

# this is sandbox for tox and go test of new style (without scons)
# it prepares sandbox, runs fetch only and leave it for next jobs which will be run parallel
- template:
    name: prepare-test-sandbox
    jobs:
      prepare-sandbox-test-sandbox:
        # it creates worker
        job-name: build-prepare-sandbox
        type: no-report
        vars:
          LINUX_DISTR: centos
          PUBLISH_TYPE: stable
          VM_TYPE: small
      fetch-sources-test-sandbox:
        job-name: build-fetch-sources
        type: no-report
        depends-on:
          - prepare-sandbox-test-sandbox
      cleanup-worker-test-sandbox:
        # it doesn't call devenv - it removes worker completly
        job-name: build-cleanup
        type: no-report,post-hook
        depends-on:
          - fetch-sources-test-sandbox

- template:
    name: test-tox-pep8
    parents:
      - prepare-test-sandbox
    jobs:
      test-unit-tox-pep8:
        job-name: test-unit-tox
        lock: tox
        depends-on:
          - fetch-sources-test-sandbox
        vars:
          TARGET_SET: pep8
          LINUX_DISTR: centos
      cleanup-worker-test-sandbox:
        depends-on:
          - test-unit-tox-pep8

- template:
    name: test-tox-unit
    parents:
      - prepare-test-sandbox
    jobs:
      test-unit-tox-unit:
        job-name: test-unit-tox
        lock: tox
        depends-on:
          - fetch-sources-test-sandbox
        vars:
          TARGET_SET: unit
          LINUX_DISTR: centos
      cleanup-worker-test-sandbox:
        depends-on:
          - test-unit-tox-unit

- template:
    name: test-tox-py36
    parents:
      - prepare-test-sandbox
    jobs:
      test-unit-tox-py36:
        job-name: test-unit-tox
        lock: tox
        depends-on:
          - fetch-sources-test-sandbox
        vars:
          TARGET_SET: py36
          LINUX_DISTR: centos
      cleanup-worker-test-sandbox:
        depends-on:
          - test-unit-tox-py36

- template:
    name: test-unit-go
    parents:
      - prepare-test-sandbox
    jobs:
      test-unit-go:
        depends-on:
          - fetch-sources-test-sandbox
        vars:
          LINUX_DISTR: centos
      cleanup-worker-test-sandbox:
        depends-on:
          - test-unit-go
