---

- template:
    name: rhosp-operator
    # to use latest deployer's code
    parents:
      - build-ubi8
    streams:
      rhosp-operator:
        vars:
          ENVIRONMENT_OS: rhel84
          TAG_SUFFIX: "-ubi8"
          ENABLE_RHEL_REGISTRATION: false
          OPENSTACK_CONTAINER_REGISTRY: "tf-mirrors.$SLAVE_REGION.$CI_DOMAIN:5005"
          NODES: 'OPENSTACK_CONTROLLER_NODES:large:1,CONTROLLER_NODES:large:1'
          CONTROL_PLANE_ORCHESTRATOR: 'operator'
    jobs:
      deploy-platform-rhosp-operator:
        stream: rhosp-operator
        job-name: deploy-platform-rhosp-operator
      deploy-tf-rhosp-operator:
        stream: rhosp-operator
        job-name: deploy-tf-rhosp-operator
        depends-on:
          - package-ubi8
          - deploy-platform-rhosp-operator
      test-sanity-rhosp-operator:
        job-name: test-sanity
        stream: rhosp-operator
        depends-on:
          - deploy-tf-rhosp-operator
      collect-logs-and-cleanup-rhosp-operator:
        job-name: collect-logs-and-cleanup
        stream: rhosp-operator
        type: post-hook
        depends-on:
          - deploy-platform-rhosp-operator
          - deploy-tf-rhosp-operator
          - test-sanity-rhosp-operator

