---

- template:
    name: build-centos
    streams:
      build-centos:
        vars:
          LINUX_DISTR: centos
    jobs:
      prepare-sandbox-centos:
        # it creates worker
        job-name: build-prepare-sandbox
        stream: build-centos
        vars:
          DEVENV_TAG: frozen
      fetch-sources-centos:
        job-name: build-fetch-sources
        stream: build-centos
        depends-on:
          - prepare-sandbox-centos
      configure-centos:
        job-name: build-configure
        stream: build-centos
        depends-on:
          - fetch-sources-centos
      package-deployers-centos:
        job-name: build-package-deployers
        stream: build-centos
        depends-on:
          - configure-centos
      compile-centos:
        job-name: build-compile
        stream: build-centos
        depends-on:
          - package-deployers-centos
      package-centos:
        job-name: build-package
        stream: build-centos
        depends-on:
          - compile-centos
      freeze-centos:
        job-name: build-freeze
        stream: build-centos
        depends-on:
          - package-centos
        vars:
          PUBLISH_TYPE: frozen
      cleanup-centos:
        # it doesn't call devenv - it removes worker completly
        job-name: build-cleanup
        stream: build-centos
        type: post-hook
        depends-on:
          - freeze-centos

- template:
    name: build-rocky9
    streams:
      build-rocky9:
        vars:
          LINUX_DISTR: rockylinux
          LINUX_DISTR_VER: 9
          TAG_SUFFIX: "-rocky9"
    jobs:
      prepare-sandbox-rocky9:
        # it creates worker
        job-name: build-prepare-sandbox
        stream: build-rocky9
        vars:
          DEVENV_TAG: frozen
      fetch-sources-rocky9:
        job-name: build-fetch-sources
        stream: build-rocky9
        depends-on:
          - prepare-sandbox-rocky9
      configure-rocky9:
        job-name: build-configure
        stream: build-rocky9
        depends-on:
          - fetch-sources-rocky9
      package-deployers-rocky9:
        job-name: build-package-deployers
        stream: build-rocky9
        depends-on:
          - configure-rocky9
      compile-rocky9:
        job-name: build-compile
        stream: build-rocky9
        depends-on:
          - package-deployers-rocky9
      package-rocky9:
        job-name: build-package
        stream: build-rocky9
        depends-on:
          - compile-rocky9
      freeze-rocky9:
        job-name: build-freeze
        stream: build-rocky9
        depends-on:
          - package-rocky9
        vars:
          PUBLISH_TYPE: frozen
      cleanup-rocky9:
        # it doesn't call devenv - it removes worker completly
        job-name: build-cleanup
        stream: build-rocky9
        type: post-hook
        depends-on:
          - freeze-rocky9

- template:
    name: build-ubi
    streams:
      build-ubi:
        vars:
          LINUX_DISTR: tf-mirrors.$SLAVE_REGION.$CI_DOMAIN:5005/ubi7/ubi
          LINUX_DISTR_VER: stable
          TAG_SUFFIX: "-ubi7"
          INSECURE_REGISTRIES: tf-mirrors.$SLAVE_REGION.$CI_DOMAIN:5005
    jobs:
      prepare-sandbox-ubi:
        # it creates worker
        job-name: build-prepare-sandbox
        stream: build-ubi
        vars:
          PUBLISH_TYPE: stable
      fetch-sources-ubi:
        job-name: build-fetch-sources
        stream: build-ubi
        depends-on:
          - prepare-sandbox-ubi
      configure-ubi:
        job-name: build-configure
        stream: build-ubi
        depends-on:
          - fetch-sources-ubi
      package-deployers-ubi:
        job-name: build-package-deployers
        stream: build-ubi
        depends-on:
          - configure-ubi
      compile-ubi:
        job-name: build-compile
        stream: build-ubi
        depends-on:
          - package-deployers-ubi
      package-ubi:
        job-name: build-package
        stream: build-ubi
        depends-on:
          - compile-ubi
      cleanup-ubi:
        # it doesn't call devenv - it removes worker completly
        job-name: build-cleanup
        stream: build-ubi
        type: post-hook
        depends-on:
          - package-ubi

- template:
    name: build-ubi-debuginfo
    streams:
      build-ubi-debuginfo:
        vars:
          LINUX_DISTR: tf-mirrors.$SLAVE_REGION.$CI_DOMAIN:5005/ubi7/ubi
          LINUX_DISTR_VER: stable
          TAG_SUFFIX: "-ubi7"
          INSECURE_REGISTRIES: tf-mirrors.$SLAVE_REGION.$CI_DOMAIN:5005
          DEBUGINFO: "TRUE"
    jobs:
      prepare-sandbox-ubi-debuginfo:
        # it creates worker
        job-name: build-prepare-sandbox
        stream: build-ubi-debuginfo
        vars:
          PUBLISH_TYPE: stable
      fetch-sources-ubi-debuginfo:
        job-name: build-fetch-sources
        stream: build-ubi-debuginfo
        depends-on:
          - prepare-sandbox-ubi-debuginfo
      configure-ubi-debuginfo:
        job-name: build-configure
        stream: build-ubi-debuginfo
        depends-on:
          - fetch-sources-ubi-debuginfo
      package-deployers-ubi-debuginfo:
        job-name: build-package-deployers
        stream: build-ubi-debuginfo
        depends-on:
          - configure-ubi-debuginfo
      compile-ubi-debuginfo:
        job-name: build-compile
        stream: build-ubi-debuginfo
        depends-on:
          - package-deployers-ubi-debuginfo
      package-ubi-debuginfo:
        job-name: build-package
        stream: build-ubi-debuginfo
        depends-on:
          - compile-ubi-debuginfo
      cleanup-ubi-debuginfo:
        # it doesn't call devenv - it removes worker completly
        job-name: build-cleanup
        stream: build-ubi-debuginfo
        type: post-hook
        depends-on:
          - package-ubi-debuginfo

- template:
    name: build-r24.1-centos
    streams:
      build-r24.1-centos:
        voting: false
        vars:
          LINUX_DISTR: centos
          GERRIT_BRANCH: "R24.1"
          TAG_SUFFIX: "-r24.1-centos"
    jobs:
      prepare-sandbox-r24.1-centos:
        # it creates worker
        job-name: build-prepare-sandbox
        stream: build-r24.1-centos
        vars:
          PUBLISH_TYPE: stable
      fetch-sources-r24.1-centos:
        job-name: build-fetch-sources
        stream: build-r24.1-centos
        depends-on:
          - prepare-sandbox-r24.1-centos
      configure-r24.1-centos:
        job-name: build-configure
        stream: build-r24.1-centos
        depends-on:
          - fetch-sources-r24.1-centos
      package-deployers-r24.1-centos:
        job-name: build-package-deployers
        stream: build-r24.1-centos
        depends-on:
          - configure-r24.1-centos
      compile-r24.1-centos:
        job-name: build-compile
        stream: build-r24.1-centos
        depends-on:
          - package-deployers-r24.1-centos
      package-r24.1-centos:
        job-name: build-package
        stream: build-r24.1-centos
        depends-on:
          - compile-r24.1-centos
      cleanup-r24.1-centos:
        # it doesn't call devenv - it removes worker completly
        job-name: build-cleanup
        stream: build-r24.1-centos
        type: post-hook
        depends-on:
          - package-r24.1-centos

- template:
    name: build-ubi8
    streams:
      build-ubi8:
        vars:
          ENVIRONMENT_OS: rhel84
          LINUX_DISTR: tf-mirrors.$SLAVE_REGION.$CI_DOMAIN:5005/ubi8/ubi
          LINUX_DISTR_VER: stable
          TAG_SUFFIX: "-ubi8"
          INSECURE_REGISTRIES: tf-mirrors.$SLAVE_REGION.$CI_DOMAIN:5005
          CONTRAIL_PARALLEL_BUILD: false
    jobs:
      prepare-sandbox-ubi8:
        # it creates worker
        job-name: build-prepare-sandbox
        stream: build-ubi8
        vars:
          PUBLISH_TYPE: stable
      fetch-sources-ubi8:
        job-name: build-fetch-sources
        stream: build-ubi8
        depends-on:
          - prepare-sandbox-ubi8
      configure-ubi8:
        job-name: build-configure
        stream: build-ubi8
        depends-on:
          - fetch-sources-ubi8
      package-deployers-ubi8:
        job-name: build-package-deployers
        stream: build-ubi8
        depends-on:
          - configure-ubi8
      compile-ubi8:
        job-name: build-compile
        stream: build-ubi8
        depends-on:
          - package-deployers-ubi8
      package-ubi8:
        job-name: build-package
        stream: build-ubi8
        depends-on:
          - compile-ubi8
      cleanup-ubi8:
        # it doesn't call devenv - it removes worker completly
        job-name: build-cleanup
        stream: build-ubi8
        type: post-hook
        depends-on:
          - package-ubi8

- template:
    name: build-ubi8-debuginfo
    streams:
      build-ubi8-debuginfo:
        vars:
          ENVIRONMENT_OS: rhel84
          LINUX_DISTR: tf-mirrors.$SLAVE_REGION.$CI_DOMAIN:5005/ubi8/ubi
          LINUX_DISTR_VER: stable
          TAG_SUFFIX: "-ubi8"
          INSECURE_REGISTRIES: tf-mirrors.$SLAVE_REGION.$CI_DOMAIN:5005
          CONTRAIL_PARALLEL_BUILD: false
          DEBUGINFO: "TRUE"
    jobs:
      prepare-sandbox-ubi8-debuginfo:
        # it creates worker
        job-name: build-prepare-sandbox
        stream: build-ubi8-debuginfo
        vars:
          PUBLISH_TYPE: stable
      fetch-sources-ubi8-debuginfo:
        job-name: build-fetch-sources
        stream: build-ubi8-debuginfo
        depends-on:
          - prepare-sandbox-ubi8-debuginfo
      configure-ubi8-debuginfo:
        job-name: build-configure
        stream: build-ubi8-debuginfo
        depends-on:
          - fetch-sources-ubi8-debuginfo
      package-deployers-ubi8-debuginfo:
        job-name: build-package-deployers
        stream: build-ubi8-debuginfo
        depends-on:
          - configure-ubi8-debuginfo
      compile-ubi8-debuginfo:
        job-name: build-compile
        stream: build-ubi8-debuginfo
        depends-on:
          - package-deployers-ubi8-debuginfo
      package-ubi8-debuginfo:
        job-name: build-package
        stream: build-ubi8-debuginfo
        depends-on:
          - compile-ubi8-debuginfo
      cleanup-ubi8-debuginfo:
        # it doesn't call devenv - it removes worker completly
        job-name: build-cleanup
        stream: build-ubi8-debuginfo
        type: post-hook
        depends-on:
          - package-ubi8-debuginfo

- template:
    name: build-ubi-deployers
    streams:
      build-ubi-deployers:
        vars:
          LINUX_DISTR: tf-mirrors.$SLAVE_REGION.$CI_DOMAIN:5005/ubi7/ubi
          LINUX_DISTR_VER: stable
          TAG_SUFFIX: "-ubi7"
          INSECURE_REGISTRIES: tf-mirrors.$SLAVE_REGION.$CI_DOMAIN:5005
    jobs:
      prepare-sandbox-ubi-deployers:
        # it creates worker
        job-name: build-prepare-sandbox
        stream: build-ubi-deployers
        vars:
          PUBLISH_TYPE: stable
      fetch-sources-ubi-deployers:
        job-name: build-fetch-sources
        stream: build-ubi-deployers
        depends-on:
          - prepare-sandbox-ubi-deployers
      configure-ubi-deployers:
        job-name: build-configure
        stream: build-ubi-deployers
        depends-on:
          - fetch-sources-ubi-deployers
      package-deployers-ubi-deployers:
        job-name: build-package-deployers
        stream: build-ubi-deployers
        depends-on:
          - configure-ubi-deployers
      cleanup-ubi-deployers:
        # it doesn't call devenv - it removes worker completly
        job-name: build-cleanup
        stream: build-ubi-deployers
        type: post-hook
        depends-on:
          - package-deployers-ubi-deployers
