- name: "find {{ item }} file"
  find:
    paths:
      - "{{ ssh_keys_dir }}"
    patterns: "{{ item }}_rsa"
    recurse: no
    file_type: file
  delegate_to: localhost
  register: keyfile

- name: "put {{ item }} to list of available keys"
  set_fact:
    key_list: "{{ key_list | combine({ item: lookup('file', keyfile.files[0].path) }) }}"
  when: keyfile.files|length == 1
